support setting sticky cookie max age
traefik/traefik pull request #10154
Opened 2023-10-06 03:54 UTC by Patrick0308

### What does this PR do?

Close #1939 

### Motivation

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

2023-10-12 09:29 UTC, rtribotte requested changes
Hello @Patrick0308,

Thanks for this contribution!

At a glance, there are a few things missing from the changes.

Whenever a new option is introduced in the dynamic configuration, the CRDs for the KubernetesCRD provider need to be regenerated.
By executing the following command they would be regenerated:
```bash
make generated-crd
```

Also, the dynamic configuration docs references need to be updated:
- adds manually the new option in `docs/content/reference/dynamic-configuration/file.toml` and in `docs/content/reference/dynamic-configuration/file.yaml`
- then run `go generate` to get the other providers dynamic configuration references updated automatically.

2023-10-16 06:58 UTC, Patrick0308 commented
@rtribotte PTAL

2023-10-16 07:04 UTC, rtribotte requested changes
Hello @Patrick0308,

Thanks for the recent changes,

I have a few suggestions, this is nitpicking but we are used to using "42" value for numbers in reference files. This is just a convention, but it is better to remain consistent.

2023-10-16 07:04 UTC, rtribotte commented on docs/content/reference/dynamic-configuration/file.toml
> +            maxAge = 1000
```suggestion
            maxAge = 42
```

2023-10-16 07:04 UTC, rtribotte commented on docs/content/reference/dynamic-configuration/file.toml
> +            maxAge = 1000
```suggestion
            maxAge = 42
```

2023-10-16 07:04 UTC, rtribotte commented on docs/content/reference/dynamic-configuration/file.yaml
> +            maxAge: 1000
```suggestion
            maxAge: 42
```

2023-10-16 07:04 UTC, rtribotte commented on docs/content/reference/dynamic-configuration/file.yaml
> +            maxAge: 1000
```suggestion
            maxAge: 42
```

2023-10-16 07:04 UTC, rtribotte commented on docs/content/reference/dynamic-configuration/kv-ref.md
> +| `traefik/http/services/Service01/loadBalancer/sticky/cookie/maxAge` | `1000` |
```suggestion
| `traefik/http/services/Service01/loadBalancer/sticky/cookie/maxAge` | `42` |
```

2023-10-16 07:04 UTC, rtribotte commented on docs/content/reference/dynamic-configuration/kv-ref.md
> +| `traefik/http/services/Service03/weighted/sticky/cookie/maxAge` | `1000` |
```suggestion
| `traefik/http/services/Service03/weighted/sticky/cookie/maxAge` | `42` |
```

2023-10-16 08:03 UTC, Patrick0308 commented
@rtribotte PTAL

2023-10-18 09:48 UTC, ldez commented
The PR should be rebased on the v3.0 branch

2023-10-18 12:01 UTC, closed without merging