Add TCP loadBalancer sourceIPs
traefik/traefik pull request #10277
Opened 2023-12-02 21:49 UTC by mzealey

### What does this PR do?

In haproxy and other loadbalancers, a `source-ip` can be specified for each connection. Linux by default only uses the primary IP of a given interface, but to get > 60k simultaneous connections to a single remote IP, multiple source IPs are required. This patch should allow an optional list of `sourceIPs` to be specified for outbound TCP connections and will use one at random if so.

I have not fully tested this patch yet, but it compiles and parses correctly and seems relatively harmless.

### Motivation

We want to use traefik to handle a large number of long-lived TCP connections.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation (partially - not sure about toml)

### Additional Notes

I'm guessing this may need to be implemented elsewhere, however TCP streaming was sufficient for our use-case.

2023-12-08 15:11 UTC, mzealey commented
Unfortunately there does not seem to be a simple way in Linux to achieve this, other than specifying the source IP address, much less something that is cross-platform portable. All large-scale proxy servers that I have seen have this sort of option for precisely this reason. I'm not convinced that 'get all IPs of the specified interface' or of the server is a sensible approach as there may be complex routing setups.

2024-03-28 14:02 UTC, juliens commented
Since we haven't found a "simple" Linux solution, we've decided to accept this pull request for review in the upcoming minor version (v3.1). Would you mind shifting your PR to the master branch and performing a rebase?

2024-04-11 13:46 UTC, jspdown requested changes

2024-04-11 13:46 UTC, jspdown commented on docs/content/routing/services/index.md
> +connections if you have multiple IP addresses on an interface.
```suggestion
Moreover, the `sourceIPs` option enables the configuration of a list of IPs, 
from which the source address for outbound connections will be selected. 
Each new connection will randomly choose a source address from the specified list.
```

2024-04-11 13:46 UTC, jspdown commented on pkg/tcp/proxy.go
>  func (p Proxy) dialBackend() (*net.TCPConn, error) {
Could you add a test, similar to `TestLookupAddress`, to make sure a source IP is obtained from a configured list?

2024-11-27 09:24 UTC, nmengin commented
Hello @mzealey,

Thanks for your contribution.

Have you planned to move forward on this PR?

2025-03-11 15:52 UTC, closed without merging