Allow TLS sessionTicketKeys config
traefik/traefik pull request #10284
Opened 2023-12-06 11:26 UTC by mzealey

### What does this PR do?

Allow specification of custom TLS session ticket keys.

Fixes #4550 

### Motivation

From the added docs:

This option allows you to specify a list of TLS Session Ticket Keys which store 
the TLS connection state on the client and allow the TLS session resumption 
with less overhead than re-establishing it from scratch. This is used in both 
TLSv1.2 Session Tickets and TLSv1.3 PSK algorithms. 
 
The use-case for this is 3-fold: 
1. If you run a cluster of Traefik servers you can put the same Session Ticket 
   Keys on all servers and then a client can use it for lightweight session 
   re-establishment to any of the servers in the cluster. By default each 
   server will have its own random keys so a ticket valid for one server would 
   not be valid for the others. 
2. Restart traefik without loosing TLS ticket validity. As the default ticket 
   keys are stored in memory, when Traefik restarts they will be lost. By 
   writing them to the config file they are persisted across restarts 
3. Custom cycling and retention periods: The default daily rotation and 7-day 
   retention periods are not customizable. You may wish to write a cronjob to 
   update the Traefik config file more or less frequently, with longer or 
   shorter retention periods. 
 
If you use this option you are responsible for key rotation, which should occur 
at least on a daily basis or Perfect Forward Secrecy is compromised. These keys 
should be stored securely or your TLS sessions may be intercepted and 
decrypted. 
 
If not specified, the default golang crypto/tls algorithm is used which is to 
keep 7 days of keys and rotate on a daily basis.  

### More

- [ ] Added/updated tests - Unsure how to write automated tests for this so basic procedure documented below
- [x] Added/updated documentation

### Additional Notes

Test like:

```
$ openssl s_client -no_tls1_3 -connect server:443 -sess_out sess < /dev/null 2>&1 |egrep 'SSL handsh|Reused|subject='
subject=CN = ssl-test4.systest.moya.app
SSL handshake has read 4171 bytes and written 316 bytes
$ openssl s_client -no_tls1_3 -connect server:443 -sess_in sess < /dev/null 2>&1 |egrep 'SSL handsh|Reused|subject='
subject=CN = ssl-test4.systest.moya.app
SSL handshake has read 287 bytes and written 427 bytes
Reused, TLSv1.3, Cipher is ECDHE-ECDSA-AES128-GCM-SHA256
```

Restarting the server and running the second command again will currently show the first output (ie no `Reused` entry), but with the patch will show a `Reused` line.

Tested with and without `-no_tls1_3` to test 1.2 and 1.3 as they use different methods.

2024-07-02 13:58 UTC, kevinpollet commented
Hello @mzealey,

Thanks for your contribution and sorry for the delay,

Please could you rebase this pull request on branch master? 
We can handle it if you want!

2024-07-23 12:26 UTC, sdelicata requested changes

2024-10-10 12:51 UTC, kevinpollet commented
Hello @mzealey,

Are you still working on this pull request?

2024-11-08 08:37 UTC, kevinpollet commented
Hello @mzealey,

Due to the lack of activity on this pull request, we are closing it.
Do not hesitate to ping us if anything changes on your end.

2024-11-08 08:37 UTC, closed without merging

2024-12-04 14:41 UTC, xjewer commented
@kevinpollet are you still keen to merge such feature request if PR to be resurrected/recreated? or is anyone else working on it?

2024-12-05 13:54 UTC, kevinpollet commented
Hi @xjewer,

> are you still keen to merge such feature request if PR to be resurrected/recreated? or is anyone else working on it?

As far as I know, no one is working on this, so feel free to open a new pull request.