New Routing Reference Documentation
traefik/traefik pull request #11330
Opened 2024-12-10 14:34 UTC by sheddy-traefik

### What does this PR do?

Following a series of discussions with @emilevauge and @nmengin, we decided to create a new reference section in the documentation. This PR  replaces the previous "Dynamic Configuration" with a new menu item called "Routing Configuration".

This PR has also been rebased on branch v3.2

### Motivation

The motivation behind this pull request is to have a more strucutured reference documentation for Traefik proxy. This new change brings a more accurate and well defined reference section in the docs. 

### More

- [x] Added/updated documentation
- [ ] Added/updated tests

2025-01-17 11:03 UTC, youkoulayley requested changes

2025-01-17 11:27 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/middlewares/ratelimit.md
> +The middleware is based on a [token bucket](https://en.wikipedia.org/wiki/Token_bucket) implementation.
fair enough

2025-01-17 11:27 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/middlewares/ratelimit.md
> +In this analogy, the `average` and `period` parameters define the **rate** at which the bucket refills, and the `burst` is the size (volume) of the bucket
got it

2025-01-17 13:37 UTC, sdelicata requested changes

2025-01-17 13:39 UTC, lbenguigui requested changes

2025-01-17 13:39 UTC, lbenguigui commented on docs/content/reference/routing-configuration/http/middlewares/replacepath.md
> +- Store the original path in a `X-Replaced-Path` header
```suggestion
- Store the original path in an `X-Replaced-Path` header
```

2025-01-17 13:39 UTC, lbenguigui commented on docs/content/reference/routing-configuration/http/middlewares/replacepath.md
> +The `replacePath1 middleware will:
```suggestion
The `replacePath` middleware will:
```

2025-01-17 13:39 UTC, lbenguigui commented on docs/content/reference/routing-configuration/http/middlewares/replacepath.md
> +    path: /foo
```suggestion
    path: "/foo"
```

2025-01-17 13:39 UTC, lbenguigui commented on docs/content/reference/routing-configuration/http/middlewares/replacepath.md
> +## Configuration Option
```suggestion
## Configuration Options
```

2025-01-17 13:39 UTC, lbenguigui commented on docs/content/reference/routing-configuration/http/middlewares/redirectscheme.md
> +The RedirectScheme middleware redirects the request if the request scheme is different from the configured scheme.
```suggestion
The `redirectScheme` middleware redirects the request if the request scheme is different from the configured scheme.
```

2025-01-17 13:40 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/middlewares/basicauth.md
> +- For security reasons, the field `users` doesn't exist for Kubernetes IngressRoute, and one should use the `secret` field instead.
I'd rewrite this statement, i don't agree with how it sounds

2025-01-17 14:35 UTC, jspdown requested changes

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +A set of forwarded headers are automatically added by default. See the [FAQ](../../../../getting-started/faq.md#what-are-the-forwarded-headers-when-proxying-http-requests) for more information.
Since we are in the reference section WDYT about relocating the list of headers from the FAQ into here?

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`customRequestHeaders`          | Lists the header names and values for requests.  | | No
```suggestion
`customRequestHeaders`          | Lists the header names and values for requests.  | [] | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`customResponseHeaders`         | Lists the header names and values for responses. |  | No
```suggestion
`customResponseHeaders`         | Lists the header names and values for responses. | [] | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`accessControlAllowHeaders`     | Specifies allowed request header names.          | | No
```suggestion
`accessControlAllowHeaders`     | Specifies allowed request header names.          | [] | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`accessControlAllowMethods`     | Specifies allowed request methods.               | | No
```suggestion
`accessControlAllowMethods`     | Specifies allowed request methods.               | [] | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`accessControlAllowOriginList`  | Specifies allowed origins. More information [here](#accesscontrolalloworiginlist)      | None      | No
```suggestion
`accessControlAllowOriginList`  | Specifies allowed origins. More information [here](#accesscontrolalloworiginlist)      | [] | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`accessControlAllowOriginListRegex` | Allows origins matching regex. More information [here](#accesscontrolalloworiginlistregex)            | None      | No
```suggestion
`accessControlAllowOriginListRegex` | Allows origins matching regex. More information [here](#accesscontrolalloworiginlistregex)            | []      | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`accessControlExposeHeaders`    | Specifies which headers are safe to expose to the API of a CORS API specification.       |      | No
```suggestion
`accessControlExposeHeaders`    | Specifies which headers are safe to expose to the API of a CORS API specification.       | []  | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`allowedHosts`                  | Lists allowed domain names.                      | None      | No
```suggestion
`allowedHosts`                  | Lists allowed domain names.                      | []      | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`hostsProxyHeaders`             | Specifies header keys for proxied hostname.      | None      | No
```suggestion
`hostsProxyHeaders`             | Specifies header keys for proxied hostname.      | []      | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`sslProxyHeaders`               | Defines a set of header keys with associated values that would indicate a valid HTTPS request. It can be useful when using other proxies (example: `"X-Forwarded-Prot
```suggestion
`sslProxyHeaders`               | Defines a set of header keys with associated values that would indicate a valid HTTPS request. It can be useful when using other proxies (example: `"X-Forwarded-Proto": "https"`).        | {}     | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`customFrameOptionsValue`       | allows the `X-Frame-Options` header value to be set with a custom value. This overrides the `FrameDeny` option.  |      | No
```suggestion
`customFrameOptionsValue`       | allows the `X-Frame-Options` header value to be set with a custom value. This overrides the `FrameDeny` option.  | ""    | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`customBrowserXSSValue`         | allows the `X-XSS-Protection` header value to be set with a custom value. This overrides the `BrowserXssFilter` option.   | | No
```suggestion
`customBrowserXSSValue`         | allows the `X-XSS-Protection` header value to be set with a custom value. This overrides the `BrowserXssFilter` option.   | false | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`contentSecurityPolicy`         | allows the `Content-Security-Policy` header value to be set with a custom value.           | | No
```suggestion
`contentSecurityPolicy`         | allows the `Content-Security-Policy` header value to be set with a custom value.           | false | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`contentSecurityPolicyReportOnly` | allows the `Content-Security-Policy-Report-Only` header value to be set with a custom value.    |    | No
```suggestion
`contentSecurityPolicyReportOnly` | allows the `Content-Security-Policy-Report-Only` header value to be set with a custom value.    | ""   | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`publicKey`                     | Implements HPKP for certificate pinning.         | | No
```suggestion
`publicKey`                     | Implements HPKP for certificate pinning.         | "" | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`referrerPolicy`                | Controls forwarding of `Referer` header.         | | No
```suggestion
`referrerPolicy`                | Controls forwarding of `Referer` header.         | "" | No
```

2025-01-17 14:35 UTC, jspdown commented on docs/content/reference/routing-configuration/http/middlewares/headers.md
> +`permissionsPolicy`             | allows sites to control browser features.                   | None      | No
```suggestion
`permissionsPolicy`             | allows sites to control browser features.                   | ""      | No
```

2025-01-17 14:37 UTC, rtribotte requested changes

2025-01-17 14:37 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/tls/overview.md
> +Traefik supports HTTPS & TLS, which concerns roughly two parts of the configuration: routers, and the TLS connection (and its underlying certificates).
I think the whole sentence should be rephrased.
TLS configuration helps to define how to handle TLS negociation with incoming connections, I'm not sure why mentioning routers, aside mentioning that the TLS configuration is done on routers.

2025-01-17 14:37 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/tls/tls-certificates.md
> +| `caCertificates` | Defines the the paths to PEM encoded CA Certificates that can be used to authenticate an ACME server with an HTTPS certificate not issued by a CA in the system-wide trusted root
```suggestion
| `caCertificates` | Defines the paths to PEM encoded CA Certificates that can be used to authenticate an ACME server with an HTTPS certificate not issued by a CA in the system-wide trusted root list. | [] | No |
```

2025-01-17 14:37 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/tls/tls-certificates.md
> +## Let's Encrypt
I think most of this section contains "Install documentation" and certificate resolvers, is it expected here?

2025-01-21 12:59 UTC, mmatur requested changes

2025-01-21 12:59 UTC, mmatur commented on docs/content/reference/routing-configuration/other-providers/nomad.md
> +
traefik.http.routers.<router_name>.rulesyntax is missing
traefik.http.routers.<router_name>.observability.accesslogs is missing
traefik.http.routers.<router_name>.observability.tracing is missing
traefik.http.routers.<router_name>.observability.metrics is missing

2025-01-21 12:59 UTC, mmatur commented on docs/content/reference/routing-configuration/other-providers/nomad.md
> +
traefik.http.services.<service_name>.loadbalancer.server.weight is missing

2025-01-21 12:59 UTC, mmatur commented on docs/content/reference/routing-configuration/other-providers/nomad.md
> +
traefik.tcp.routers.<router_name>.ruleSyntax is missing
traefik.tcp.routers.<router_name>.priority is missing

2025-01-21 12:59 UTC, mmatur commented on docs/content/reference/routing-configuration/other-providers/nomad.md
> +
traefik.tcp.services.<service_name>.loadbalancer.terminationdelay is missing

2025-01-21 12:59 UTC, mmatur commented on docs/content/reference/routing-configuration/other-providers/nomad.md
> +
Middleware section is missing

2025-01-21 12:59 UTC, mmatur commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +??? example "Automatic service creation and assignment with labels"
As written in the current documentation https://doc.traefik.io/traefik/routing/providers/swarm/#services

Label: `traefik.http.services.myservice.loadbalancer.server.port=8080` is mandatory to swarm provider

2025-01-21 12:59 UTC, mmatur commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +
traefik.http.routers.<router_name>.rulesyntax is missing
traefik.http.routers.<router_name>.observability.accesslogs is missing
traefik.http.routers.<router_name>.observability.tracing is missing
traefik.http.routers.<router_name>.observability.metrics is missing

2025-01-21 12:59 UTC, mmatur commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +
traefik.http.services.<service_name>.loadbalancer.server.weight is missing

2025-01-21 12:59 UTC, mmatur commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +        labels:
Indentation is not correct

2025-01-21 12:59 UTC, mmatur commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +
traefik.tcp.routers.<router_name>.ruleSyntax is missing

2025-01-21 12:59 UTC, mmatur commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +
traefik.tcp.services.<service_name>.loadbalancer.terminationDelay is missing

2025-01-21 12:59 UTC, mmatur commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +
TCP middleware section is missing

2025-01-23 09:32 UTC, juliens requested changes

2025-01-23 09:32 UTC, juliens commented on docs/content/reference/routing-configuration/kubernetes/tcp/ingressroutetcp.md
> +| `routes[n].services[n].nodePortLB`            | Controls, when creating the load-balancer, whether the LB's children are directly the nodes internal IPs using the nodePort when the service type is.
```suggestion
| `routes[n].services[n].nodePortLB`            | Controls, when creating the load-balancer, whether the LB's children are directly the nodes internal IPs using the nodePort when the service type is NodePort. It allows services to be reachable when Traefik runs externally from the Kubernetes cluster but within the same network of the nodes. | false | no |
```

2025-01-27 11:25 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/middlewares/stripprefix.md
> +## Configuration Options
i believe this option has been deprecated, and there's a warning that it should not be used, so there's no point documenting it.

2025-01-27 15:34 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/router/rules-and-priority.md
this has been split into several pages

2025-01-27 15:43 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/tls/tls-certificates.md
> +## Let's Encrypt
I think i mixed things up, i'll take out the rest of the section

2025-01-27 15:47 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/load-balancing/serverstransport.md
> +| `serverstransport.`<br />`rootcas` | Set of root certificate authorities to use when verifying server certificates. (for mTLS connections). |  | No |
what do you mean?

2025-01-27 15:49 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/load-balancing/serverstransport.md
> +| `serverstransport.`<br />`rootcas` | Set of root certificate authorities to use when verifying server certificates. (for mTLS connections). |  | No |
got this from here: https://doc.traefik.io/traefik/routing/services/#certificates

2025-01-27 16:03 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/consul-catalog.md
> +
there's no need for this one as the tags themselves are examples

2025-01-27 16:15 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/dynamic-configuration-methods.md
> +    ```
updated

2025-01-27 16:17 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/middlewares/errorpages.md
> +
done

2025-01-27 16:18 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/middlewares/forwardauth.md
> +| `tls.insecureSkipVerify` | During TLS connections, accepts any certificate presented by the server regardless of the host names it covers. | false | No |
done

2025-01-27 16:18 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/middlewares/digestauth.md
> +- If both `users` and `usersFile` are provided, the two are merged. The contents of `usersFile` have precedence over the values in `users`.
done

2025-01-27 16:20 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/middlewares/contenttype.md
> +    Therefore, it has no effect against any other `Content-Type` header modifications (e.g.: in another middleware such as compress).
fixed

2025-01-27 16:20 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/middlewares/stripprefix.md
> +---
added

2025-01-27 16:21 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/middlewares/replacepathregex.md
> +
i've included it

2025-01-27 16:22 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/middlewares/circuitbreaker.md
> +| `checkPeriod` | The interval between successive checks of the circuit breaker condition (when in standby state). | 100ms | No |
I've standardized state instead of status

2025-01-29 09:54 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +
added

2025-01-29 09:54 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +
can't find this option in any of the previous docs

2025-01-29 09:54 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +
can't find this option in any of the previous docs

2025-01-29 09:54 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +        labels:
fixed

2025-01-29 10:03 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +??? example "Automatic service creation and assignment with labels"
updated

2025-01-29 10:03 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/nomad.md
> +
added

2025-01-29 10:03 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/nomad.md
> +
can't find this option in any of the previous docs

2025-01-29 10:03 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/nomad.md
> +
can't find the rulesyntax option in any of the previous docs

2025-01-29 10:03 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/nomad.md
> +
added

2025-01-29 10:04 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/nomad.md
> +
can't find the rulesyntax option in any of the previous docs

2025-01-29 10:04 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +    | `traefik/tcp/services/<service_name>/weighted/services/0/weight` | `42`  |
middleware section has been added but i cannot find entry for any of the options above in any of our previous docs

2025-01-29 10:05 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +
can't find this option in any of the previous docs

2025-01-29 10:06 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +
can't find this option in any of the previous docs

2025-01-29 10:07 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +
can't find these options in any of the previous docs, maybe they were missed before too

2025-01-29 10:07 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +
can't find these options in any of the previous docs

2025-01-29 10:07 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +
can't find these options in any of the previous docs

2025-01-29 10:07 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +
can't find ruleSyntax anywhere

2025-01-29 10:08 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/ecs.md
> +
added

2025-01-29 10:08 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/ecs.md
> +
added

2025-01-29 10:08 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/ecs.md
> +
added

2025-01-29 10:08 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/ecs.md
> +
added

2025-01-29 10:09 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/docker.md
> +
added

2025-01-29 10:09 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/consul-catalog.md
> +
also cannot find rulesyntax in any of our docs

2025-01-29 10:09 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/consul-catalog.md
> +
added

2025-01-29 10:10 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/consul-catalog.md
> +
added

2025-02-03 16:34 UTC, nmengin commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +
@sheddy-traefik the option is [here](https://doc.traefik.io/traefik/routing/routers/#rulesyntax)

2025-02-03 16:35 UTC, nmengin commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +
@sheddy-traefik the option is [here](https://doc.traefik.io/traefik/routing/services/#terminationdelay)

2025-02-05 12:11 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/consul-catalog.md
> +
https://doc.traefik.io/traefik/v3.1/routing/services/#terminationdelay

i believe this has been moved to servertransport level

2025-02-05 12:11 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/docker.md
> +
https://doc.traefik.io/traefik/v3.1/routing/services/#terminationdelay

i believe this has been moved to servertransport level

2025-02-05 12:20 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +
https://doc.traefik.io/traefik/v3.1/routing/services/#failover-service

i believe this is only possible with the file provider

2025-02-05 12:28 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +
found, added

2025-02-05 12:28 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +
added

2025-02-05 12:31 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +
added

2025-02-05 12:32 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/docker.md
> +
added

2025-02-05 12:32 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/ecs.md
> +
added

2025-02-05 12:36 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +
https://doc.traefik.io/traefik/v3.1/routing/services/#terminationdelay

i believe this has been moved to servertransport level

2025-02-05 12:36 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/swarm.md
> +
updated

2025-02-05 12:37 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +
https://doc.traefik.io/traefik/v3.1/routing/services/#terminationdelay

i believe this has been moved to servertransport level

2025-02-07 08:55 UTC, lbenguigui commented on docs/content/reference/routing-configuration/http/middlewares/stripprefixregex.md
> +## Configuration Example
```suggestion
## Configuration Examples
```

2025-02-10 12:48 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/middlewares/stripprefixregex.md
> +## Configuration Example
It's just one example, so it can't be examples :)

2025-02-11 10:23 UTC, rtribotte requested changes

2025-02-11 10:23 UTC, rtribotte commented on docs/content/reference/routing-configuration/tcp/tls.md
> +      # will terminate the TLS request by default
```suggestion
      # Enable TLS termination for all requests.
```

2025-02-11 10:23 UTC, rtribotte commented on docs/content/reference/routing-configuration/tcp/tls.md
> +    # will terminate the TLS request by default
```suggestion
    # Enable TLS termination for all requests.
```

2025-02-11 10:23 UTC, rtribotte commented on docs/content/reference/routing-configuration/tcp/tls.md
> +|`options`| enables fine-grained control of the TLS parameters. It refers to a [TLS Options](../http/tls/tls-certificates.md#tls-options) and will be applied only if a `HostSNI` rule is defined. |  |
```suggestion
|`options`| enables fine-grained control of the TLS parameters. It refers to a [TLS Options](../http/tls/tls-certificates.md#tls-options) and will be applied only if a `HostSNI` rule is defined. | "" | No |
```

2025-02-11 10:23 UTC, rtribotte commented on docs/content/reference/routing-configuration/tcp/tls.md
> +|`domains`| Defines a set of SANs (alternative domains) for each main domain. Every domain must have A/AAAA records pointing to Traefik. Each domain & SAN will lead to a certificate request.|  | No |
```suggestion
|`domains`| Defines a set of SANs (alternative domains) for each main domain. Every domain must have A/AAAA records pointing to Traefik. Each domain & SAN will lead to a certificate request.| [] | No |
```

2025-02-11 10:23 UTC, rtribotte commented on docs/content/reference/routing-configuration/tcp/tls.md
> +|`certResolver`| If defined, Traefik will try to generate certificates based on routers `Host` & `HostSNI` rules. |  | No |
```suggestion
|`certResolver`| If defined, Traefik will try to generate certificates based on routers `Host` & `HostSNI` rules. | "" | No |
```

2025-02-11 10:24 UTC, kevinpollet requested changes

2025-02-11 15:52 UTC, kevinpollet requested changes

2025-02-11 15:52 UTC, kevinpollet commented on docs/content/reference/routing-configuration/kubernetes/http/traefikService.md
To be consistent with other files I would rename this file to `traefikservice`.

2025-02-11 15:52 UTC, kevinpollet commented on docs/content/reference/routing-configuration/kubernetes/http/traefikService.md
> +A `TraefikService` is a custom resource that can be put on top of the Kubernetes Services. It brings advanced load-balancing feature such as a [Weighted Round Robin](#weighted-round-robin) load balan
Maybe here we should also add a sentence to about the need of Traefik CRDs.

2025-02-11 15:52 UTC, kevinpollet commented on docs/content/reference/routing-configuration/kubernetes/http/traefikService.md
> +| `services[m].`<br />`kind` | Kind of the service targeted.<br />Two values allowed:<br />- **Service**: Kubernetes Service<br /> **TraefikService**: Traefik Service.<br />More information [here](#s
```suggestion
| `services[m].`<br />`kind` | Kind of the service targeted.<br />Two values allowed:<br />- **Service**: Kubernetes Service<br /> - **TraefikService**: Traefik Service.<br />More information [here](#services). | "" | No |
```

2025-02-11 15:52 UTC, kevinpollet commented on docs/content/reference/routing-configuration/kubernetes/http/traefikService.md
> +### ExternalName Service
If we want to keep, I would move it at the send of the page, as it seems that this section is only required for healthcheck config explanation.

2025-02-11 15:52 UTC, kevinpollet commented on docs/content/reference/routing-configuration/kubernetes/http/ingressroute.md
> +| `routes[n].`<br />`services[m].`<br />`kind` | Kind of the service targeted.<br />Two values allowed:<br />- **Service**: Kubernetes Service<br /> **TraefikService**: Traefik Service.<br />More inf
```suggestion
| `routes[n].`<br />`services[m].`<br />`kind` | Kind of the service targeted.<br />Two values allowed:<br />- **Service**: Kubernetes Service<br /> **TraefikService**: Traefik Service.<br />More information [here](#routesservices). | "" | No |
```

2025-02-11 15:52 UTC, kevinpollet commented on docs/content/reference/routing-configuration/kubernetes/http/ingressroute.md
> +### routes.services
Same here IMO the naming of those sections is a bit confusing.

2025-02-11 15:52 UTC, kevinpollet commented on docs/content/reference/routing-configuration/kubernetes/http/ingressroute.md
> +### routes.services
```suggestion
### Services
```

2025-02-11 15:52 UTC, kevinpollet commented on docs/content/reference/routing-configuration/kubernetes/http/ingressroute.md
> +### routes.middlewares
```suggestion
### Middlewares
```

2025-02-11 15:52 UTC, kevinpollet commented on docs/content/reference/routing-configuration/kubernetes/http/ingressroute.md
> +### tls.options
```suggestion
### TLS Options
```

2025-02-11 16:05 UTC, kevinpollet requested changes

2025-02-12 10:46 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/ingressroute.md
I don't think that is necessary to be honest, this would mean restructuring the entire docs structure we had initially

2025-02-12 10:49 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/ingress.md
> +## Configuration Example
Yes, you're correct

2025-02-12 10:52 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/ingress.md
> +    as stated in [this documentation](https://kubernetes.io/docs/concepts/services-networking/ingress/#multiple-matches).
I'll take it off

2025-02-12 10:56 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/ingressroute.md
We do have that already 
<img width="216" alt="Screenshot 2025-02-12 at 10 55 24 AM" src="https://github.com/user-attachments/assets/29fbeee0-976d-4d3c-a6d6-bf8d191c87d1" />

2025-02-12 10:57 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/ingressroute.md
I think it makes sense more to keep it this way and arrange them by their protocols

2025-02-12 10:58 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/udp/ingressrouteudp.md
see my comment above

2025-02-12 10:58 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/ingressroute.md
> +## Configuration Example
I'd take it off, no problem for me

2025-02-12 11:20 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/router/observability.md
> +```
I don't thinks so to be fair, the configuration example already shows all the options. The only reason i made a section for metrics was to include the note about metrics layer.

2025-02-12 12:10 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/tls/overview.md
> +When a router has to handle HTTPS traffic, it should be specified with a `tls` field of the router definition.
what do you suggest?

2025-02-12 12:48 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/tcp/ingressroutetcp.md
> +### routes.services
Will remove it

2025-02-12 13:15 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/tlsstore.md
> +`TLSStore` is the CRD implementation of a [Traefik TLS Store](./tlsstore.md). Register the `TLSStore` kind in the Kubernetes cluster before creating `TLSStore` objects.
Okay

2025-02-12 13:16 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/tlsstore.md
> +`TLSStore` is the CRD implementation of a [Traefik TLS Store](./tlsstore.md). Register the `TLSStore` kind in the Kubernetes cluster before creating `TLSStore` objects.
Yep

2025-02-12 13:16 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/tlsstore.md
> +| `name`                                 | Name of the TLS Store. Only the `default` store name is taken into account yet.  |          | Yes      |
yeah, that works

2025-02-12 13:20 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/tlsstore.md
> +| `certificates`                         | List of Kubernetes [Secrets](https://kubernetes.io/docs/concepts/configuration/secret/), each of them holding a key/certificate pair to add to the store. Li
Fixed

2025-02-12 13:43 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/middleware.md
> +More information about available middlewares in the dedicated [middlewares section](../../http/middlewares/overview.md).
I don't really see the need since we've linked to the middleware page, we will only be duplicating content.

2025-02-12 13:52 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/traefikService.md
> +### ExternalName Service
I'll remove it completely, I was supposed to clean that up

2025-02-12 14:05 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/traefikService.md
> +### Kubernetes Service vs TraefikService
Rewrote the introduction

2025-02-12 14:45 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/gateway-api.md
> +The Kubernetes Gateway API provider supports version [v1.2.0](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.3.0) of the specification.
updated this

2025-02-12 14:46 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/ingress.md
> +
updated

2025-02-12 14:49 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/tls/tls-certificates.md
Updated the menu item to include TLS certs and options as seperate pages

2025-02-12 14:51 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/udp/ingressrouteudp.md
> +| `routes[n].services[n].nativeLB`    | Controls, when creating the load-balancer, whether the LB's children are directly the pods IPs or if the only child is the Kubernetes Service clusterIP. | fals
done

2025-02-12 14:54 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/middleware.md
> +## Configuration Example
Done

2025-02-12 14:56 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/tcp/ingressroutetcp.md
> +#### ExternalName Service
updated

2025-02-12 15:13 UTC, rtribotte commented on docs/content/reference/routing-configuration/dynamic-configuration-methods.md
> +- Other Providers (Consul, Nomad, etc.) : Use tags.
The new doc structure introduces two new concepts, install configuration and routing configuration, and are quite the replacement for static and dynamic configuration, so for new comers I find it maybe too raw to not introduce what dynamic configuration is, i.e. the previous concept for routing configuration.

2025-02-12 15:18 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/tls/overview.md
> +When a router has to handle HTTPS traffic, it should be specified with a `tls` field of the router definition.
I'm not sure, I think you should remove that line from that overview and make sure the information is easily accessible elsewhere, my point is I think it might be overlooked if it's just put in an overview like that.

2025-02-12 16:50 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/tls/overview.md
> +When a router has to handle HTTPS traffic, it should be specified with a `tls` field of the router definition.
Ah i see, that makes a lot more sense

2025-02-12 16:50 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/dynamic-configuration-methods.md
> +- Other Providers (Consul, Nomad, etc.) : Use tags.
Ah got it

2025-02-13 08:53 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/router/observability.md
> +    To enable router-level observability, you must first enable access-logs, tracing, and metrics.
```suggestion
    To enable router-level observability, you must first enable access-logs, tracing, and metrics.
    When metrics layers are not enabled with the `addEntryPointsLabels`, `addRoutersLabels` and/or `addServicesLabels` options,
    enabling metrics for a router will not enable them.
```

2025-02-13 08:55 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/router/observability.md
> +```
@sheddy-traefik Ok got it, so maybe we could remove this whole metrics details section and just give that hint in the info note above (see my suggestion)

2025-02-13 09:25 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/router/observability.md
> +    To enable router-level observability, you must first enable access-logs, tracing, and metrics.
makes sense

2025-02-13 09:25 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/router/observability.md
> +```
works for me

2025-02-13 15:27 UTC, sdelicata requested changes

2025-02-13 15:27 UTC, sdelicata commented on docs/content/reference/routing-configuration/http/middlewares/basicauth.md
> +# Also note that dollar signs should NOT be doubled when they not evaluated (e.g. Ansible docker_container module).
```suggestion
# Also, note that dollar signs should NOT be doubled when not evaluated (e.g. Ansible docker_container module).
```

2025-02-13 15:27 UTC, sdelicata commented on docs/content/reference/routing-configuration/http/middlewares/chain.md
> +It makes it effortless to reuse the same groups
```suggestion
It makes it effortless to reuse the same groups.
```

2025-02-13 15:27 UTC, sdelicata commented on docs/content/reference/routing-configuration/http/middlewares/circuitbreaker.md
> +There are three possible state for your circuit breaker:
```suggestion
There are three possible states for your circuit breaker:
```

2025-02-13 18:48 UTC, sheddy-traefik commented
Hey @emilevauge & @nmengin i've update the General Routing section with the feedback you provided on the examples.

You can find these changes in this commit: https://github.com/traefik/traefik/pull/11330/commits/f908c82f0f58d7e88ee2537fcf17f4d750c0fe33

cc: @kevinpollet @rtribotte

2025-02-14 09:11 UTC, lbenguigui commented on docs/content/reference/routing-configuration/http/middlewares/replacepath.md
> +- Store the original path in a `X-Replaced-Path` header
```suggestion
- Store the original path in an `X-Replaced-Path` header
```

2025-02-14 09:25 UTC, lbenguigui approved these changes
LGTM

2025-02-14 13:33 UTC, youkoulayley approved these changes
LGTM 👍

2025-02-14 13:40 UTC, kevinpollet commented on docs/content/reference/routing-configuration/http/middlewares/compress.md
> +The `compress` middleware compresses response. It supports Gzip, Brotli and Zstandard compression
```suggestion
The `compress` middleware compresses response. It supports Gzip, Brotli and Zstandard compression.
```

2025-02-14 14:28 UTC, jspdown requested changes

2025-02-14 14:56 UTC, sdelicata approved these changes
LGTM

2025-02-17 14:10 UTC, jspdown approved these changes
LGTM 👍

2025-02-20 10:37 UTC, rtribotte requested changes
Since the reference for the static configuration (the full list of all static configuration options) is not accessible to the reader, I feel like a dedicated section for the experimental configuration is needed.
Most of the experimental options, when they are feature flags, are documented in place where the associated feature is documented, but for instance, plugins related experimental options (like `abortOnfailure`) are not documented at all.

2025-02-20 10:37 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/router/observability.md
> +The default router observability configuration is inherited from the attached EntryPoints and can be configured with the observability [options](../../../install-configuration/entrypoints.md#configur
```suggestion
By default, the router observability configuration is inherited from the attached EntryPoints and can be configured with the observability [options](../../../install-configuration/entrypoints.md#configuration-options)).
```

2025-02-20 10:37 UTC, rtribotte commented on docs/content/reference/routing-configuration/tcp/router/observability.md
> +The default router observability configuration is inherited from the attached EntryPoints and can be configured with the observability [options](../../../install-configuration/entrypoints.md#configur
```suggestion
By default, the router observability configuration is inherited from the attached EntryPoints and can be configured with the observability [options](../../../install-configuration/entrypoints.md#configuration-options)).
```

2025-02-20 10:37 UTC, rtribotte commented on docs/content/reference/routing-configuration/udp/router/observability.md
> +The default router observability configuration is inherited from the attached EntryPoints and can be configured with the observability [options](../../../install-configuration/entrypoints.md#configur
```suggestion
By default, the router observability configuration is inherited from the attached EntryPoints and can be configured with the observability [options](../../../install-configuration/entrypoints.md#configuration-options)).
```

2025-02-20 10:37 UTC, rtribotte commented on docs/mkdocs.yml
> +        - 'Other Providers' :
WDYT of:
```suggestion
        - 'Label and Tag Providers' :
```

2025-02-20 10:39 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/router/observability.md
> +The default router observability configuration is inherited from the attached EntryPoints and can be configured with the observability [options](../../../install-configuration/entrypoints.md#configur
Since we have multiple "default" resources concepts, I find it less confusing.

2025-02-20 10:59 UTC, sheddy-traefik commented on docs/mkdocs.yml
> +        - 'Other Providers' :
I've updated it regardless, i think its fine because in the examples through out the routing config, we now have tabs for labels & tags so it makes sense.

2025-02-21 10:45 UTC, kevinpollet requested changes

2025-02-21 11:12 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/tlsoption.md
@nmengin @emilevauge wdyt about this idea?

2025-02-21 11:23 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/ingressroute.md
> +In Kubernetes, you can use the Traefik `IngressRoute` to define a router.
Done

2025-02-21 11:25 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/tcp/serverstransporttcp.md
> +This registers the `ServersTransportTCP` kind and other Traefik-specific resources.
done

2025-02-21 11:26 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/tlsoption.md
Reading this again, i'm not sure what you mean

2025-02-21 11:29 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/tlsstore.md
> +## Configuration Example
removed it

2025-02-21 15:58 UTC, kevinpollet commented on docs/content/reference/routing-configuration/kubernetes/http/tlsoption.md
I mean that today in the kubernetes folder tree we have md files for gateway and ingress and also folders containing the resource descriptions for the CRD provider. I would change the folders structure to something like:

kubernetes
 - crd
   - http
   - tcp
   - udp
 - gatewayapi.md
 - ingress.md  

Does it make sense?

2025-02-21 15:59 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/tlsoption.md
Ah yes, it does, i'd do this then

2025-02-24 11:11 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/http/tlsoption.md
Hey @kevinpollet i've updated the folder structure based on your suggestion in this commit: https://github.com/traefik/traefik/pull/11330/commits/7717339b9927bee06f6e28c3c9c8e9b165c2165a

2025-03-03 10:27 UTC, rtribotte commented on docs/content/reference/routing-configuration/udp/router/observability.md
The whole page is innacurate, as there is no observability for UDP routers.

2025-03-03 10:27 UTC, rtribotte commented on docs/content/reference/routing-configuration/tcp/router/observability.md
The whole page is inaccurate, as there is no observability for TCP routers.

2025-03-03 10:27 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/router/observability.md
> +```
Kubernetes Ingress and CRDs are not covered here, but this is missing as well in there dedicated section.

2025-03-03 10:31 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/tls/tls-certificates.md
> +```
Hmm, what do you mean? i'm being careful about mixing content from different sections of the doc.

2025-03-03 10:33 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/tcp/router/observability.md
Interesting, i didn't know this, will remove.

2025-03-03 10:35 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/router/observability.md
> +```
I'll add them in, Emile wants us to limit examples to those few above that's why i didn't include it. If you think it is absolutely necessary then i can include it.

2025-03-03 10:39 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/router/observability.md
> +```
I'll add them in, Emile wants us to limit examples to those few above that's why i didn't include it. If you think it is absolutely necessary then i can include it.

2025-03-03 10:45 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/tls/tls-certificates.md
> +```
My idea is, let's say you're only interested in the Docker provider, and you jump to that section, you wouldn't know how to configure the default generated certificate, would you?

2025-03-03 10:50 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/tls/tls-certificates.md
> +```
Well fair enough, I'll include a note in the providers pages that links to this section of the page.

2025-03-03 10:50 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/router/observability.md
> +```
It should be enough to document the `observability` configuration node within Kubernetes Ingress and CRDs pages. I doubled checked, it probably something that has been lost in translation since you opened this PR and the documentation for the `observability` configuration node has been merged.

2025-03-03 10:52 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/router/observability.md
> +```
Okay

2025-03-03 10:52 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/tls/tls-certificates.md
> +```
okay

2025-03-03 14:41 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/tls/tls-options.md
@sheddy-traefik Yes sorry, my comment was unclear.
The TLSOptions attachement to a router is well documented.

However, the definition of a TLSOptions resource is not documented in any provider specific page, except the CRD one that has it's own resource to define it.

It makes sense, since TLSOptions can't be defined label or tag providers.
But, with KV providers, it is possible (this is messy and due to historical reasons that I could explain if you want)...

So I think we could document how to define a TLSOptions with KV provider, but also state the limitation clearly in the "main" section.
WDYT?

2025-03-04 15:40 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/tls/tls-options.md
makes sense

2025-03-04 16:42 UTC, sheddy-traefik commented
@rtribotte updated the PR with your suggestions here: https://github.com/traefik/traefik/pull/11330/commits/6cc881a53425828d251661d6ff85ea114a6889db

2025-03-05 07:01 UTC, mmatur approved these changes

2025-03-05 14:16 UTC, nmengin requested changes
Hey @sheddy-traefik,$

Thanks a lot for this huge PR 👏 

Please find below a few suggestions on TCP.

2025-03-05 14:16 UTC, nmengin commented on docs/content/reference/routing-configuration/http/router/rules-and-priority.md
> +The default value of the `ruleSyntax` option is inherited from the `defaultRuleSyntax` option in the static configuration. By default, the `defaultRuleSyntax` static option is v3, meaning that the de
Shouldn't we talk about install configuration?

```suggestion
The default value of the `ruleSyntax` option is inherited from the `defaultRuleSyntax` option in the install configuration (formerly known as static configuration) By default, the `defaultRuleSyntax` option is v3, meaning that the default rule syntax is also v3
```

2025-03-05 14:16 UTC, nmengin commented on docs/content/reference/routing-configuration/kubernetes/crd/tcp/serverstransporttcp.md
> +    If no `serversTransportTCP` is specified, the `default@internal` will be used. The `default@internal` `serversTransportTCP` is created from the static configuration.
Shouldn't we talk about install configuration?
```suggestion
    If no `serversTransportTCP` is specified, the `default@internal` will be used. The `default@internal` `serversTransportTCP` is created from the install configuration (formerly known as static configuration)
```

2025-03-05 14:16 UTC, nmengin commented on docs/content/reference/routing-configuration/tcp/serverstransport.md
> +    Please note that SPIFFE must be enabled in the [static configuration](../../install-configuration/tls/spiffe.md) before using it to secure the connection between Traefik and the backends.
Shouldn't we talk about install configuration?

```suggestion
    Please note that SPIFFE must be enabled in the [install configuration](../../install-configuration/tls/spiffe.md) (formerly known as static configuration) before using it to secure the connection between Traefik and the backends.
```

2025-03-05 14:16 UTC, nmengin commented on docs/content/reference/routing-configuration/kubernetes/crd/tcp/ingressroutetcp.md
> +
The example seems to be missing.

2025-03-05 15:06 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/kubernetes/crd/tcp/ingressroutetcp.md
> +
included

2025-03-05 15:32 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/router/rules-and-priority.md
> +
```suggestion

```yaml tab="Labels"
services:
  my-container:
    #...
    labels:
      - "traefik.http.routers.Router-1.rule=HostRegexp(`[a-z]+\.traefik\.com`)
      - "traefik.http.routers.Router-2.rule=Host(`foobar.traefik.com`)
```

```json tab="Tags"
  {
    "Name": "my-service",
    "Tags": [
      "traefik.http.routers.Router-1.rule=HostRegexp(`[a-z]+\.traefik\.com`)",
      "traefik.http.routers.Router-2.rule=Host(`foobar.traefik.com`)",
    ]
    // ...
  }
```

```

2025-03-05 15:33 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/router/rules-and-priority.md
> +
Tags and Labels examples are missing here, but the suggestion doesn't seem to work.

2025-03-05 15:36 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/router/rules-and-priority.md
> +  }
```suggestion
  {
    "Name": "my-service",
    "Tags": [
      "traefik.http.routers.Router-v3.rule=HostRegexp(`[a-z]+\\.traefik\\.com`)",
      "traefik.http.routers.Router-v3.ruleSyntax=v3"
      "traefik.http.routers.Router-v2.rule=HostRegexp(`{subdomain:[a-z]+}.traefik.com`)",
      "traefik.http.routers.Router-v2.ruleSyntax=v2"
    ]
    // ...
  }
```

I would simplify all Tags configuration examples that are similar to this one in this way.

2025-03-05 15:37 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/router/rules-and-priority.md
> +    "Name": "Routers",
```suggestion
    "Name": "my-service",
```

2025-03-05 15:43 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/router/observability.md
> +```
okay, i agree too

2025-03-05 15:44 UTC, rtribotte commented on docs/content/reference/routing-configuration/http/load-balancing/service.md
> +## Configuration Example
Tags and Labels examples are missing here.

2025-03-05 15:51 UTC, rtribotte approved these changes
Thanks!

2025-03-05 16:08 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/load-balancing/service.md
I clearly understand what you mean, the reason i kept it this way is because there are more than one concept for services, merging them as one might be confusing for the reader. It'll be oversimplifying a complex topic. It is for this season i kept things separate.

2025-03-05 16:11 UTC, kevinpollet requested changes

2025-03-05 16:24 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/http/load-balancing/service.md
> +## Configuration Example
included

2025-03-06 08:55 UTC, kevinpollet approved these changes
Thanks 👍

2025-03-07 10:56 UTC, nmengin requested changes
@sheddy-traefik 

New round, I reviewed UDP as well.

2025-03-07 10:56 UTC, nmengin commented on docs/content/reference/routing-configuration/other-providers/nomad.md
> +
This section is not well placed.

```suggestion
```

2025-03-07 10:56 UTC, nmengin commented on docs/content/reference/routing-configuration/other-providers/nomad.md
> +### UDP
The TCP middelware was no well placed.

```suggestion
#### TCP Middleware

You can declare pieces of middleware using tags starting with `traefik.tcp.middlewares.{name-of-your-choice}.`, followed by the middleware type/options.

For example, to declare a middleware [`InFlightConn`](../tcp/middlewares/inflightconn.md) named `test-inflightconn`, you'd write `traefik.tcp.middlewares.test-inflightconn.inflightconn.amount=10`.

More information about available middlewares in the dedicated [middlewares section](../tcp/middlewares/overview.md).

??? example "Declaring and Referencing a Middleware"
    
    ```yaml
    # ...
    # Declaring a middleware
    traefik.tcp.middlewares.test-inflightconn.amount=10
    # Referencing a middleware
    traefik.tcp.routers.my-service.middlewares=test-inflightconn
    ```

!!! warning "Conflicts in Declaration"

    If you declare multiple middleware with the same name but with different parameters, the middleware fails to be declared.

### UDP
```

2025-03-07 10:56 UTC, nmengin commented on docs/content/reference/routing-configuration/other-providers/ecs.md
> +
Change the order of the sections:

```suggestion
#### TCP Middleware

You can declare pieces of middleware using tags starting with `traefik.tcp.middlewares.{name-of-your-choice}.`, followed by the middleware type/options.

For example, to declare a middleware [`InFlightConn`](../tcp/middlewares/inflightconn.md) named `test-inflightconn`, you'd write `traefik.tcp.middlewares.test-inflightconn.inflightconn.amount=10`.

More information about available middlewares in the dedicated [middlewares section](../tcp/middlewares/overview.md).

??? example "Declaring and Referencing a Middleware"
    
    ```yaml
    # ...
    # Declaring a middleware
    traefik.tcp.middlewares.test-inflightconn.amount=10
    # Referencing a middleware
    traefik.tcp.routers.my-service.middlewares=test-inflightconn
    ```

!!! warning "Conflicts in Declaration"

    If you declare multiple middleware with the same name but with different parameters, the middleware fails to be declared.

### UDP

You can declare UDP Routers and/or Services using tags.

??? example "Declaring UDP Routers and Services"

    ```yaml
    traefik.udp.routers.my-router.entrypoints=udp
    traefik.udp.services.my-service.loadbalancer.server.port=4123
    ```

!!! warning "UDP and HTTP"

    If you declare a UDP Router/Service, it will prevent Traefik from automatically creating an HTTP Router/Service (like it does by default if no UDP Router/Service is defined).
    You can declare both a UDP Router/Service and an HTTP Router/Service for the same elastic service (but you have to do so manually).

```

2025-03-07 10:56 UTC, nmengin commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +| `traefik/tls/stores/Store0/defaultGeneratedCert/resolver`                       | `foobar`       |
@sheddy-traefik could you add a UDP section?
It was missing in the current documentation 😅

2025-03-07 10:56 UTC, nmengin commented on docs/content/reference/routing-configuration/udp/router/rules-priority.md
> +the implementation of an UDP router in Traefik Hub relies on what we (and a couple of other implementations) call a `session`.
```suggestion
the implementation of an UDP router in Traefik relies on what we (and a couple of other implementations) call a `session`.
```

2025-03-07 10:56 UTC, nmengin commented on docs/content/reference/routing-configuration/udp/router/rules-priority.md
> +
Could you add examples with labels and tags, please?

2025-03-07 10:56 UTC, nmengin commented on docs/content/reference/routing-configuration/udp/service.md
> +
Could you add examples with labels and tags?

2025-03-07 12:29 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/udp/service.md
> +
Based on the Docker provider code, the UDP server address is computed automatically from the container’s IP and port during container inspection. The docker provider’s function for UDP services always sets the address (via net.JoinHostPort(ip, port)) regardless of any label you might try to provide. see [here](https://github.com/traefik/traefik/blob/07e6491ace82b55be7f6881d11737821a41501d5/pkg/provider/docker/config.go#L228)

So, you cannot define the `udp.services.my-service.loadBalancer.servers.address` manually using labels—the value is gotten from the container’s runtime details. If you need to explicitly set the address, you would have to use a static (file provider) configuration instead.

Same for tags, for example [see here](https://github.com/traefik/traefik/blob/07e6491ace82b55be7f6881d11737821a41501d5/pkg/provider/nomad/config.go#L233) for the definition in the nomad provider

Also, Refer to: https://doc.traefik.io/traefik/reference/dynamic-configuration/nomad/ & https://doc.traefik.io/traefik/reference/dynamic-configuration/docker/

2025-03-07 12:56 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +| `traefik/tls/stores/Store0/defaultGeneratedCert/resolver`                       | `foobar`       |
done

2025-03-07 12:56 UTC, sheddy-traefik commented on docs/content/reference/routing-configuration/other-providers/nomad.md
> +### UDP
Updated

2025-03-07 12:57 UTC, sheddy-traefik commented
@nmengin i've updated the PR with your review here: https://github.com/traefik/traefik/pull/11330/commits/d9bfb75c0b4b8c4fea9c9b936846e36050a6db39

2025-03-10 09:38 UTC, nmengin requested changes
Latest comment before LGTM 😉

2025-03-10 09:38 UTC, nmengin commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +### UDP Routers
```suggestion
#### UDP Routers
```

2025-03-10 09:38 UTC, nmengin commented on docs/content/reference/routing-configuration/other-providers/kv.md
> +### UDP Services
```suggestion
#### UDP Services
```

2025-03-10 09:58 UTC, juliens approved these changes
LGTM

2025-03-10 13:54 UTC, nmengin approved these changes
LGTM 🎉 

Thank you @sheddy-traefik 🙏

2025-03-10 14:28 UTC, merged