Add passive health checks
traefik/traefik pull request #11351
Opened 2024-12-17 03:02 UTC by Nelwhix

### What does this PR do?

Adding Passive Health Checks 

### Motivation

Fixes #11306 

### More

- [ x] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

2024-12-17 03:09 UTC, Nelwhix commented
My goal for how this will work will be 
```yaml
http:
  services:
    my-service:
      loadBalancer:
        servers:
        - url: "http://<private-ip-server-1>:<private-port-server-1>/"
           healthCheck:
             maxFails: 3
             failTimeout: 30
```
I added the implementation to just http services for now.

2025-02-14 15:46 UTC, youkoulayley requested changes
Hello @Nelwhix 
Thanks for your contribution.

I have a few suggestions.

2025-02-14 15:46 UTC, youkoulayley commented on pkg/healthcheck/healthcheck.go
> +}
Could you move this struct below, next to the `NewPassiveHealthChecker` function ?

2025-02-14 15:46 UTC, youkoulayley commented on pkg/healthcheck/healthcheck.go
> +	for _, t := range p.Failures {
```suggestion
	threshold := now.Add(time.Duration(-p.failTimeout))

	var filteredFailures []time.Time
	for _, t := range p.Failures {
```

2025-02-15 05:15 UTC, Nelwhix commented on pkg/healthcheck/healthcheck.go
> +	Failures    []time.Time
true, changed it

2025-02-15 05:22 UTC, Nelwhix commented on pkg/server/service/loadbalancer/wrr/wrr.go
> +	}
added

2025-02-15 05:29 UTC, Nelwhix commented on pkg/server/service/loadbalancer/wrr/wrr.go
> +	"github.com/traefik/traefik/v3/pkg/healthcheck"
done

2025-02-15 05:32 UTC, Nelwhix commented on pkg/healthcheck/healthcheck.go
> +}
okay

2025-02-28 08:24 UTC, youkoulayley requested changes
Just a small import to fix remaining

2025-02-28 08:24 UTC, youkoulayley commented on pkg/healthcheck/healthcheck.go
> +
```suggestion
```

2025-03-07 13:21 UTC, youkoulayley approved these changes
LGTM

2025-03-14 09:57 UTC, jspdown commented
Hello @Nelwhix and thanks for your contribution.

Before reviewing the content of the PR I wanted to discuss how this feature is configured. 
First of all, I really like the `failTimeout` and `maxFails`, it's very easy to understand. In the future, if needed, we could even add an additional `recoverTimeout` to define how long to wait before recovering a server, and this without breaking change. 

Though, I'm wondering if we really want this to be configured at the server level. This would be the right spot if we wanted each server to have a different passive healthcheck config, or a mix of server with and without passive healthcheck under the same loadbalancer. I might be wrong but I have the feeling that most of the time we want to have a uniform config on the loadbalancer. 

Did you considered moving this configuration one layer up in the loadbalancer?

2025-03-14 10:09 UTC, Nelwhix commented
Hi @jspdown, I was trying to achieve nginx style passive health checks https://docs.nginx.com/nginx/admin-guide/load-balancer/http-health-check/

2025-04-11 14:06 UTC, sdelicata requested changes
Hi @Nelwhix! Thanks for your contribution.
I've made a few comments/suggestions.

2025-04-27 04:57 UTC, Nelwhix commented on pkg/server/service/loadbalancer/wrr/wrr.go
> +	customWriter := &CustomResponseWriter{ResponseWriter: w, StatusCode: http.StatusOK}
what if I modify the loop in nextServer to:

```go
for {
  // Pick handler with closest deadline.
  handler = heap.Pop(b).(*namedHandler)
  
  // curDeadline should be handler's deadline so that new added entry would have a fair competition environment with the old ones.
  b.curDeadline = handler.deadline
  handler.deadline += 1 / handler.weight
  
  heap.Push(b, handler)
  
  // Skip if:
  if _, down := b.status[handler.name]; !down {
      continue
  }

  if _, isFenced := b.fenced[handler.name]; isFenced {
      continue
  }

  if handler.passiveHealthChecker != nil && !handler.passiveHealthChecker.AllowRequest() {
      continue
  }
}
```

With this we don't need nextServerExcluding... the filtering happens when selecting a server

2025-04-27 04:58 UTC, Nelwhix commented on pkg/server/service/loadbalancer/wrr/wrr.go
> +type CustomResponseWriter struct {
dibe

2025-04-27 04:58 UTC, Nelwhix commented on pkg/server/service/loadbalancer/wrr/wrr.go
> +	wantsPassiveHealthCheck bool
fixed

2025-04-27 04:58 UTC, Nelwhix commented on pkg/server/service/loadbalancer/wrr/wrr.go
> +func (b *Balancer) nextServerExcluding(handlerName string) (*namedHandler, error) {
added

2025-04-27 04:58 UTC, Nelwhix commented on pkg/server/service/loadbalancer/wrr/wrr.go
fixed, also added tests to check

2025-05-09 15:39 UTC, sdelicata requested changes

2025-05-09 15:39 UTC, sdelicata commented on pkg/server/service/loadbalancer/wrr/wrr.go
> +	customWriter := &StatusRecorder{ResponseWriter: w, StatusCode: http.StatusOK}
Could you rename the `customWriter` var accordingly, please?

2025-05-09 15:39 UTC, sdelicata commented on pkg/server/service/loadbalancer/wrr/wrr.go
> +	customWriter := &CustomResponseWriter{ResponseWriter: w, StatusCode: http.StatusOK}
Yes, personally, I prefer this approach.

2025-05-17 14:25 UTC, Nelwhix commented on pkg/server/service/loadbalancer/wrr/wrr.go
> +	customWriter := &CustomResponseWriter{ResponseWriter: w, StatusCode: http.StatusOK}
Done

2025-05-19 07:36 UTC, sdelicata requested changes

2025-05-19 07:36 UTC, sdelicata commented on docs/content/routing/services/index.md
> +- failTimeout (default: 10s) – the window during which failures are counted, and the duration the server remains marked unhealthy.
```suggestion
#### Passive Health Checks
Passive health checks rely on real traffic to assess server health.
Traefik forwards requests as usual and evaluates each response or timeout,
incrementing a failure counter whenever a request fails.
If the number of failures within a specified time window exceeds the configured threshold,
Traefik will automatically stop routing traffic to that server until it recovers.

The following options are available for passive health checks:
- maxFails (default: 1) –  The number of failed requests required before the server is considered unhealthy.

- failTimeout (default: 10s) – The time window during which failures are counted, and the duration for which the server remains marked as unhealthy.
```

2025-05-19 07:36 UTC, sdelicata commented on pkg/config/dynamic/http_config.go
> +	// FailTimeout sets the time during which a number of failed attempts must happen for the server to be marked unavailable.
```suggestion
	// FailTimeout defines the time window during which a certain number of failed attempts must occur for the server to be marked as unavailable.
```

2025-05-19 07:36 UTC, sdelicata commented on pkg/config/dynamic/http_config.go
>  	FailTimeout ptypes.Duration `json:"failTimeout,omitempty" toml:"failTimeout,omitempty" yaml:"failTimeout,omitempty" export:"true"`
The current name `FailTimeout` is ambiguous, as it suggests a request timeout or delay between retries.
Renaming it to `FailureWindow` (or `FailurePeriod`) better reflects its actual role: defining the time frame during which failed attempts are counted before marking a server as unhealthy. WDYT?

2025-05-19 07:36 UTC, sdelicata commented on pkg/config/dynamic/http_config.go
> +	// MaxFails sets the number of failed attempts that must occur during the fail timeout.
```suggestion
	// MaxFails is the number of failed attempts allowed within the failure window before marking the server as unhealthy.
```

2025-05-19 07:36 UTC, sdelicata commented on pkg/config/dynamic/http_config.go
> +	MaxFails int `json:"maxFails,omitempty" toml:"maxFails,omitempty" yaml:"maxFails,omitempty" export:"true"`
`MaxFails` is slightly ambiguous to me.
WDYT about replacing it with `FailureThreshold` (or `MaxFailedAttempts`) to improve clarity, making it easier to understand that it sets the limit of allowed failures within the failure window before a server is marked as unhealthy?

2025-05-21 01:19 UTC, Nelwhix commented on pkg/config/dynamic/http_config.go
>  	FailTimeout ptypes.Duration `json:"failTimeout,omitempty" toml:"failTimeout,omitempty" yaml:"failTimeout,omitempty" export:"true"`
I changed to FailureWindow

2025-05-21 01:19 UTC, Nelwhix commented on pkg/config/dynamic/http_config.go
> +	MaxFails int `json:"maxFails,omitempty" toml:"maxFails,omitempty" yaml:"maxFails,omitempty" export:"true"`
I changed to MaxFailedAttempts

2025-05-23 07:33 UTC, sdelicata requested changes, later dismissed
Thanks @Nelwhix for your improvements.
There are still some linting errors to fix, then we should be ready.

2025-05-30 13:33 UTC, lbenguigui requested changes, later dismissed

2025-05-30 13:33 UTC, lbenguigui commented on pkg/server/service/loadbalancer/wrr/wrr.go
> +		if _, down := b.status[handler.name]; !down {
Unless I missed something, `b.status` indicates whether a server is up. Maybe renaming `down` to something like up would make the logic clearer?

2025-05-30 13:33 UTC, lbenguigui commented on pkg/server/service/loadbalancer/wrr/wrr.go
> +		if handler.passiveHealthChecker != nil && !handler.passiveHealthChecker.AllowRequest() {
I think there might be an issue: if there's one server up but it has a passive health check that disallows requests, we wait until `failTimeout` expires. 
Is that the intended behavior? Should we instead return an `errNoAvailableServer` in this case?

2025-06-04 09:28 UTC, kevinpollet commented
Hello @Nelwhix and thanks for this contribution,

After some consideration, we think that the passive health check mechanism should be configured at the load balancer level, in line with the active health checker configuration (see https://doc.traefik.io/traefik/routing/services/#health-check). This means that, once configured, the passive health check will be enabled for all servers.

We also think that it should reuse the current status updater mechanism. This would make the passive health checker responsible for propagating the server status to its parent (the load balancer). It should also be responsible for updating the `ServiceInfo`, which is needed to update the server status on the UI, as well as the corresponding `ServerUpGauge` metric (see https://github.com/traefik/traefik/blob/master/pkg/healthcheck/healthcheck.go#L135). This means that nothing needs to be changed in the WRR code, as the passive health checker will be integrated in the same way as the active health checker.

Regarding the passive health check algorithm, having read the documentation (https://docs.nginx.com/nginx/admin-guide/load-balancer/http-health-check/), we propose that, once a server is down, we should wait for the `FailureWindow` duration to expire before sending another request to the server. This means that, once a server is considered down, the passive health checker will have to clear its failures slice, after which a timer should be set to update the server status to 'up' once the `FailureWindow` duration has expired.

Does it make sense?
Are you ok with updating this pull request in that direction?

2025-06-04 23:23 UTC, Nelwhix commented
@kevinpollet Okay Kevin, I will rework

2025-06-22 19:25 UTC, Nelwhix commented
Hi @kevinpollet , I was able to implement most of your suggestions. except for the passive health checker to update the ServiceInfo and serverupguage. I tried to pass in the metrics and serviceinfo to the `wrr.Balancer` and then use the healthchecker to do `p.balancer.info.update` but that will lead to cyclic import errors. Please could you point me in a better direction?

2025-07-24 07:46 UTC, kevinpollet commented
Hello @Nelwhix, and apologies for the delay.

It's a bit difficult to reason through the cyclic import issue without working directly with the code.
Would it be okay with you if we push review commits while conducting the pull request review?

2025-07-24 08:21 UTC, Nelwhix commented
Okay @kevinpollet

2025-08-21 09:16 UTC, rtribotte approved these changes
Thanks!

2025-08-21 09:17 UTC, kevinpollet approved these changes
Thanks 👍

2025-08-21 09:40 UTC, merged