Allow to use regular expressions for `AccessControlAllowOriginList`
traefik/traefik pull request #6881
Opened 2020-06-03 13:44 UTC by jodosha

## What does this PR do?

This PR allows to use regular expressions to be used as `AccessControlAllowOriginList` value.

### Motivation

Regular expressions brings more flexibility to the configuration. We're working on a SOA environment that requires temporary hosts to be spun for development and demo purposes. Having a fixed list of hosts requires to frequently update Traefik configuration.

See also https://github.com/containous/traefik/issues/6851

### More

- [x] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

Because `AccessControlAllowOriginList` is of type `[]string`, I leveraged `regexp.MatchString(pattern string, s string)` (the utility function from the `regexp` package) instead of `Regexp.MatchString(s string)` (the exported function from `Regexp` type).

In this way the configuration can define regular expressions as strings. This works with the current code type structure. It also avoids to compile regexps, but at the same time it handle malformed ones (see the tests).

However, there is a limitation regarding `regexp.MatchString`. According to its [documentation](https://golang.org/pkg/regexp/#MatchString):

> More complicated queries need to use Compile and the full Regexp interface.

But I believe that this is a problem that we won't hit.

2020-06-03 21:28 UTC, jodosha commented
On a second thought (credit goes to @barthez), the current proposed solution can be a potential breaking change / security problem.

Imagine an **existing** company that uses a fixed host as a value for `AccessControlAllowOriginList`, for instance: `https://foo.bar.co`, if an incoming request that sets `Origin` to `https://foo.bar.company` the existing match fails because the two strings are different, but because of this PR, it will try the regular expression fallback, which it will pass, even if it shouldn't.

You can have a demonstration, by applying this patch to the PR:

```diff
diff --git a/pkg/middlewares/headers/headers_test.go b/pkg/middlewares/headers/headers_test.go
index 0b751f3e..1ed87a9a 100644
--- a/pkg/middlewares/headers/headers_test.go
+++ b/pkg/middlewares/headers/headers_test.go
@@ -412,13 +412,13 @@ func TestCORSResponses(t *testing.T) {
 		{
 			desc: "Test Simple Request",
 			header: NewHeader(emptyHandler, dynamic.Headers{
-				AccessControlAllowOriginList: []string{"https://foo.bar.org"},
+				AccessControlAllowOriginList: []string{"https://foo.bar.co"},
 			}),
 			requestHeaders: map[string][]string{
-				"Origin": {"https://foo.bar.org"},
+				"Origin": {"https://foo.bar.company"},
 			},
 			expected: map[string][]string{
-				"Access-Control-Allow-Origin": {"https://foo.bar.org"},
+				"Access-Control-Allow-Origin": {"https://foo.bar.company"},
 			},
 		},
 		{
```

---

I believe that the PR cannot be merged as it is, but I'm looking for maintainers advice on how to proceed. Thanks in advance.

2020-06-18 14:16 UTC, jodosha commented
👋  Do you have any news? Thanks in advance 😄

2020-08-03 09:42 UTC, jbdoumenjou commented
Hello @jodosha,

Thanks for your contribution!
We prefer to have a new option such as "AccessControlAllowOriginListRegex", to avoid having a breaking change and imposing a potential performance loss for users who do not have this need.

What do you think?

2020-08-28 08:01 UTC, ToGo101 commented
Just want to leave a +1 here for this feature.

2020-09-11 12:41 UTC, jbdoumenjou commented
:wave: @jodosha, do you think you will have some time to work on it ? 
Thanks

2020-10-28 13:09 UTC, kevinpollet requested changes
Just minor comments 👍

2020-10-28 13:09 UTC, kevinpollet commented on pkg/middlewares/headers/header.go
> +			log.WithoutContext().Debugf("an error occurred during origin parsing: %v", err)
Maybe it's better to log an `Error` here, WDYT?

```suggestion
			log.WithoutContext().Errof("Unable to match origin: %v", err)
```

2020-10-28 13:09 UTC, kevinpollet commented on pkg/middlewares/headers/header_test.go
> +			desc: "Regexp Origin Request",
Maybe here we could add a test for a non-matching origin, wdyt?

2020-10-28 14:53 UTC, jbdoumenjou approved these changes
LGTM

2020-10-28 14:56 UTC, kevinpollet approved these changes
LGTM, Nice work 👍

2020-10-29 08:08 UTC, rtribotte approved these changes
LGTM 👍

2020-10-29 09:52 UTC, merged

2020-11-17 08:36 UTC, jodosha commented
Thank you all. ❤️

2021-04-23 02:12 UTC, codefriar commented
@jodosha - I don't suppose you have an example of this working in a toml file? I've tried this:

```
    cors-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - HEAD
          - POST
        accessControlMaxAge: 100
        addVaryHeader: true
        accessControlAllowOriginListRegex:
          - https://.*\.foo\.com$
 ```

Yet this doesn't seem to be working :(

2021-04-23 07:24 UTC, jbdoumenjou commented
Hello @codefriar,
Thanks for your interest in Traefik!

For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik). :smiley: