Add Kubernetes Gateway Provider
traefik/traefik pull request #7416
Opened 2020-10-13 14:30 UTC by rtribotte

### What does this PR do?

This PR brings a new provider for the Kubernetes Gateway API.
The current implementation provides a first step to support the new Kubernetes Gateway API, and it's currently focused on supporting HTTPRoute only.

At the time of the opening of this PR:
- The code uses the [Service APIs](https://github.com/kubernetes-sigs/service-apis/) SIGs project [v0.1.0](https://github.com/kubernetes-sigs/service-apis/releases/tag/v0.1.0) tag.
- Only basic `HTTP` and `HTTPS` scenarios are supported
  - with `Host`, `Header` and `Path` rules
  - that refers to a Kubernetes `Service`
  - with TLS certificate defined in a Kubernetes `Secret`

### Motivation

fixes #7258
Propose a first implementation of Kubernetes Gateway API specification.

### More

 - [x] Added/updated tests
 - [x] Added/updated documentation

### Additional Notes

This PR will remain a work in progress until the first stable version of Kubernetes Gateway API.
Therefore, more features will be added in the meantime.

Co-authored-by: Jean-Baptiste Doumenjou <925513+jbdoumenjou@users.noreply.github.com>

2020-11-26 08:31 UTC, kevinpollet requested changes

2020-11-26 10:28 UTC, kevinpollet commented on docs/content/reference/dynamic-configuration/kubernetes-gateway.md
> +Dynamic configuration with Kubernetes Gateway provider
```suggestion
Dynamic configuration with Kubernetes Gateway provider.
```

2020-11-26 11:39 UTC, kevinpollet commented on pkg/provider/kubernetes/gateway/kubernetes.go
> +				if httpRoute == nil {
Are you sure that this check is really necessary? 

I think the Kubernetes provider will not return an array with `nil` inside.

2020-11-26 11:39 UTC, kevinpollet commented on pkg/provider/kubernetes/gateway/kubernetes.go
> +	if len(httpRouteSpec.Hostnames) > 0 {
I think this check is not necessary because the `hostRule` will be empty as we will not iterate on the `httpRouteSpec.Hostnames`.

2020-11-26 11:39 UTC, kevinpollet commented on pkg/provider/kubernetes/gateway/kubernetes.go
> +		if match.Path.Type == v1alpha1.PathMatchExact {
Maybe it's just a matter of taste but I would have used a `switch` here, and add a log if the user has used an unsupported path `Type` matching, wdyt?

2020-11-26 11:39 UTC, kevinpollet commented on pkg/provider/kubernetes/gateway/kubernetes.go
> +				if forwardTo.Port == 0 || p.TargetPort.IntVal == int32(forwardTo.Port) {
I think we should also check that the `TargetPort` is of `int` type, because the `TargetPort` of a service can reference a container port by name.

2020-12-03 11:02 UTC, jbdoumenjou commented on pkg/provider/kubernetes/gateway/kubernetes.go
> +							listenerStatuses[i].Conditions = append(listenerStatuses[i].Conditions, metav1.Condition{
They omit to update this comment accordingly to the update of the Gateway Status.

2020-12-03 11:13 UTC, jbdoumenjou commented on pkg/provider/kubernetes/gateway/client.go
> +		// TODO: add real label selector
As it is the first step, we will not apply a specific filter.

2020-12-03 14:19 UTC, rtribotte commented on pkg/provider/kubernetes/gateway/client.go
> +		_, err := c.csGateway.NetworkingV1alpha1().GatewayClasses().UpdateStatus(ctx, gc, metav1.UpdateOptions{})
We don't reuse the GatewayClass after updating it, so for now, we'll keep it as is

2020-12-03 14:22 UTC, rtribotte commented on pkg/provider/kubernetes/gateway/kubernetes.go
> +
Should be ok by now

2020-12-04 11:41 UTC, jspdown commented on pkg/provider/kubernetes/gateway/kubernetes.go
> +						URL: fmt.Sprintf("%s://%s:%d", protocol, addr.IP, port),
Could you concat the IP and Port using `net.JoinHostPort`. Otherwise the URL will be invalid for IPv6 as it's expected to be `http://[2001::]:80`.

2020-12-04 11:57 UTC, kevinpollet reviewed
Just minor comments 😄

2020-12-04 11:57 UTC, kevinpollet commented on pkg/provider/kubernetes/gateway/kubernetes.go
> +				logger.Debugf("An error occurred while updating gateway status: %v", err)
I think it's better to log an error here, wdyt?

```suggestion
				logger.Errorf("An error occurred while updating gateway status: %v", err)
```

2020-12-04 11:57 UTC, kevinpollet commented on pkg/provider/kubernetes/gateway/kubernetes.go
> +			logger.Debugf("An error occurred while updating gateway status: %v", err)
Same here.

```suggestion
			logger.Errorf("An error occurred while updating gateway status: %v", err)
```

2020-12-04 11:57 UTC, kevinpollet commented on pkg/provider/kubernetes/gateway/client.go
> +	if statusEquals(g.Status, gatewayStatus) {
I'm wondering here if it's appropriate to return an `error` if the statuses are equal?
Maybe we just have to return?

2020-12-15 14:13 UTC, kevinpollet approved these changes
LGTM 👍

2020-12-15 14:13 UTC, ldez approved these changes
LGTM

2020-12-15 15:37 UTC, jbdoumenjou approved these changes
LGTM

2020-12-15 15:40 UTC, merged