Fix ingress documentation
traefik/traefik pull request #7424
Opened 2020-10-15 07:43 UTC by rtribotte

### What does this PR do?

This PR adds a TLS example for the Ingress provider, clarifies the usage of the TLS section in the Ingress Spec, cleans unnecessary elements in the first example, and re-orders elements in the TLS documentation section. 

### Motivation

Clarifies how to configure an Ingress.
related to #7420

### More

- [ ] ~Added/updated tests~
- [x] Added/updated documentation

2020-10-15 08:11 UTC, SantoDE requested changes
Only 1 minor nitpick 👼

2020-10-15 08:11 UTC, SantoDE commented on docs/content/routing/providers/kubernetes-ingress.md
> +      # Only loading certificates from Secrets, that will be used to terminate TLS traffic.
```suggestion
Only selects which certificate(s) should be loaded from the secret, in order to terminate TLS
```

2020-10-15 08:11 UTC, jbdoumenjou approved these changes
LGTM

2020-10-19 09:29 UTC, rtribotte commented on docs/content/routing/providers/kubernetes-ingress.md
> +      # Only loading certificates from Secrets, that will be used to terminate TLS traffic.
@SantoDE I made the changes :-)

2020-10-19 11:02 UTC, ldez requested changes

2020-10-19 11:02 UTC, ldez commented on docs/content/routing/providers/kubernetes-ingress.md
> +-- entrypoints.websecure.http.tls
```suggestion
--entrypoints.websecure.address=:443
--entrypoints.websecure.http.tls
```

2020-10-19 14:47 UTC, SantoDE approved these changes
LGTM

2020-10-20 12:07 UTC, ldez approved these changes
LGTM

2020-10-20 12:16 UTC, merged