Enable stats collection when pilot is enabled
traefik/traefik pull request #7483
Opened 2020-10-28 13:28 UTC by mmatur

### What does this PR do?

This PR enables stats collections when Pilot is used.

### Motivation

We activate anonymous usage when using pilot to better understand the community's need, and also to get information about plug-ins popularity

### More

- [ ] Added/updated tests
- [x] Added/updated documentation

2020-10-29 10:31 UTC, ldez approved these changes
LGTM

2020-10-29 12:19 UTC, SuperSandro2000 commented
I don't know how this will corollate with features which are missing from Traefik.

2020-10-30 10:23 UTC, SantoDE commented
Can you elaborate a bit more @SuperSandro2000? I cant really follow you.

2020-10-30 11:14 UTC, kevinpollet requested changes

2020-10-30 11:14 UTC, kevinpollet commented on docs/content/contributing/data-collection.md
> +This feature is activated when using pilot to better understand the community's need, and also to get information about plug-ins popularity.
```suggestion
This feature is activated when using Traefik Pilot to better understand the community's need, and also to get information about plug-ins popularity.
```

2020-10-30 11:30 UTC, jbdoumenjou approved these changes
LGTM

2020-10-30 11:35 UTC, SuperSandro2000 commented
> Can you elaborate a bit more @SuperSandro2000? I cant really follow you.

I don't like that Traefik force enables stats collection when I just want to use plugins which could also work without any hosted infrastructure and fully offline.

2020-10-30 14:03 UTC, kevinpollet approved these changes
LGTM

2020-10-30 15:54 UTC, merged