IngressRoute: add an option to disable cross-namespace routing
traefik/traefik pull request #7595
Opened 2020-11-26 13:53 UTC by rtribotte

### What does this PR do?

This PR adds the `enableCrossNamespace` option on the Kubernetes provider configuration to allow/disallow cross-namespace routing.
The `enableCrossNamespace` is defaulted to `true`.
When set to `false` it's not possible for an IngressRoute to reference a service in another namespace than its namespace.

### Motivation

fixes #7353

### More

- [x] Added/updated tests
- [x] Added/updated documentation

### Additional Notes

Co-authored-by: Jean-Baptiste Doumenjou <925513+jbdoumenjou@users.noreply.github.com>

2020-11-27 10:21 UTC, jspdown requested changes

2020-11-27 10:21 UTC, jspdown commented on pkg/provider/kubernetes/crd/kubernetes.go
> +	EnableCrossNamespaces  *bool           `description:"Kubernetes enable cross namespaces capacity." json:"enableCrossNamespaces,omitempty" toml:"enableCrossNamespaces,omitempty" yaml:"enableCrossName
```suggestion
	EnableCrossNamespaces  *bool           `description:"Kubernetes enable cross namespaces capability." json:"enableCrossNamespaces,omitempty" toml:"enableCrossNamespaces,omitempty" yaml:"enableCrossNamespaces,omitempty" export:"true"`
```

2020-11-27 10:35 UTC, jspdown commented
@jbdoumenjou, @rtribotte Could you add a new integration test?

2020-11-27 13:18 UTC, SantoDE commented on docs/content/providers/kubernetes-crd.md
> +
Is 2.4 correct? Like, will we do another PR to master before releasing 2.4?

2020-11-27 13:19 UTC, SantoDE commented on pkg/provider/kubernetes/crd/kubernetes.go
> +		logger.Warn("Cross-namespace referencing between Ingresses and Services is enabled, please ensure that is expected (see EnableCrossNamespaces option).")
```suggestion
logger.Warn("Cross-namespace referencing between Ingresses and Services is enabled, please ensure that this is expected (see EnableCrossNamespaces option).")
```

2020-11-27 13:22 UTC, SantoDE requested changes
just some minor stuff :)

2020-11-27 13:46 UTC, jbdoumenjou commented on docs/content/providers/kubernetes-crd.md
> +
@jspdown, it seems to be a good idea, we can enhance the documentation.
@SantoDE,  the plan was to introduce the flag without modifying the behavior, then reverse the flag to be more strict by default.

2020-11-27 15:49 UTC, SantoDE commented on docs/content/providers/kubernetes-crd.md
> +
Ok but in which versions? sorry, I dont get it 🙈

2020-12-01 14:34 UTC, jbdoumenjou commented on docs/content/providers/kubernetes-crd.md
> +
After discussions, we will allow cross namespace by default in this version and wait for user feedback.
We will reverse the flag in a future version.

2020-12-07 11:07 UTC, jspdown requested changes

2020-12-07 11:07 UTC, jspdown commented on pkg/provider/kubernetes/crd/kubernetes_test.go
> +					// The router that reference the invalid service will be discarded upper in the process
```suggestion
					// The router that references the invalid service will be discarded upper in the process
```

2020-12-07 11:07 UTC, jspdown commented on pkg/provider/kubernetes/crd/kubernetes_test.go
> +				// The router that reference the invalid service will be discarded upper in the process
```suggestion
				// The router that references the invalid service will be discarded upper in the process
```

2020-12-07 11:07 UTC, jspdown commented on pkg/provider/kubernetes/crd/kubernetes_udp.go
>  func createLoadBalancerServerUDP(client Client, namespace string, service v1alpha1.ServiceUDP) (*dynamic.UDPService, error) {
Would be nice to rename the `namespace` parameter into `parentNamespace` like you did in the createLoadBalancerServerTCP`. It's easier to understand where the namespace comes from.

2020-12-07 12:45 UTC, kevinpollet requested changes

2020-12-08 15:13 UTC, jbdoumenjou approved these changes
LGTM

2020-12-09 08:40 UTC, jspdown approved these changes
LGTM :+1:

2020-12-09 09:31 UTC, kevinpollet approved these changes
LGTM 👍

2020-12-10 13:38 UTC, ldez approved these changes
LGTM

2020-12-10 13:58 UTC, merged