Documentation: Add spacing to sidebars so the last item is always visible
traefik/traefik pull request #7616
Opened 2020-12-03 14:27 UTC by paulocfjunior

### What does this PR do?

This PR adds some spacing at the bottom of the sidebar menus on the documentation, which is sufficient to make the last item visible when there are many items and we scroll all the way down.

### Motivation

The documentation as we have today, depending on which menus are opened, the last item of the sidebar menu in the documentation (both left or right), might not be visible, because it's covered by the footer bar.
This PR should solve the issues mentioned by https://github.com/traefik/doc/issues/149 and https://github.com/traefik/doc/issues/150, in their source. So the next time we export the doc, it will be correct.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

#### Preview
![Screen Recording 2020-12-03 at 11 10 48](https://user-images.githubusercontent.com/38889364/101038678-6a332e80-355a-11eb-8565-f7bbbdb4412d.gif)

2020-12-03 15:22 UTC, ldez approved these changes
LGTM

2020-12-03 15:48 UTC, kevinpollet requested changes
I tested the change on Netlify with Firefox and it doesn't work for me but on Chrome and Safari it works fine.

Maybe something is wrong with my browser cache?

<img width="1607" alt="Capture d’écran 2020-12-03 à 16 36 38" src="https://user-images.githubusercontent.com/299142/101051633-29113d80-359f-11eb-8ff3-fd9433e8a67c.png">

2020-12-03 17:14 UTC, paulocfjunior commented
I checked here, it doesn't seem to be cache, I'll work on a solution for this that works on other browsers too.

2020-12-04 18:46 UTC, paulocfjunior commented
@kevinpollet I switched to another solution that also works for Chrome and all other modern browsers. Would you mind taking a look on it again?

2020-12-07 08:43 UTC, kevinpollet commented
Hey @paulocfjunior,

I tested your solution with `Netlify,` the left menu is fixed, but the right menu takes all the page even if there no item.
Is it the expected behaviour?

<img width="1378" alt="Capture d’écran 2020-12-05 à 11 15 26" src="https://user-images.githubusercontent.com/299142/101328442-6f111e80-3889-11eb-8899-d0039672c6cd.png">

2020-12-07 13:24 UTC, paulocfjunior commented
@kevinpollet actually it looks better if it doesn't increase its height unnecessarily, I committed a change that does that.

2020-12-07 16:36 UTC, kevinpollet approved these changes
LGTM 👍

2020-12-07 16:37 UTC, jbdoumenjou approved these changes
LGTM

2020-12-07 17:24 UTC, merged