Add Mux for TCP Routers
traefik/traefik pull request #8182
Opened 2021-06-11 17:12 UTC by dtomcej

### What does this PR do?

This PR adds:
- muxxing to TCP routers, allowing for multiple and extensible matchers to be used to match and find routes.
- A ClientIP matcher for TCP
- An SNIHost matcher for TCP

### Motivation

TCP Routing can be improved.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

- This PR adds the muxing into `github.com/traefik/traefik/v2/pkg/tcp.Router`. I'm not 100% sure that is the correct place to do this.
- This PR adds clientIP routing into router builder

2021-07-25 14:53 UTC, fkollmann commented
Hi, we need this feature. Can I help you with the implementation? Would you prefer me to fork your repo? Best Regards, Felix

2021-12-01 10:57 UTC, tomMoulard requested changes

2021-12-01 10:57 UTC, tomMoulard commented on pkg/tcp/wrr_load_balancer_test.go
> +	remoteAddr net.Addr
```suggestion
	call map[string]int
```

2021-12-01 10:57 UTC, tomMoulard commented on pkg/tcp/wrr_load_balancer_test.go
> +	return f.remoteAddr
```suggestion
	panic("implement me")
```

2021-12-01 10:57 UTC, tomMoulard commented on pkg/tcp/wrr_load_balancer_test.go
> +	remoteAddr net.Addr
Reverting this file as it has nothing to do with this PR.

2021-12-01 10:57 UTC, tomMoulard commented on pkg/anonymize/anonymize_config_test.go
> +		"foobar": &static.EntryPoint{
Reverting, useless.
```suggestion
		"foobar": {
```

2021-12-01 10:57 UTC, tomMoulard commented on pkg/server/router/tcp/manager.go
> +			logger.Debug(routerErr)
```suggestion
			logger.Error(routerErr)
```

2021-12-06 14:37 UTC, mpl commented on docs/content/routing/routers/index.md
> +??? example "Setting priorities -- using the [File Provider](../../providers/file.md)"
let's fix the HTTP counterpart instead.

2021-12-10 12:37 UTC, rtribotte commented on pkg/muxer/tcp/mux_test.go
> +		},
This is not really the same as the tests of the parser library, because here we validate that the matching is working against/among multiple values.

2021-12-10 13:31 UTC, tomMoulard commented on pkg/muxer/tcp/mux_test.go
> +		},
ok :smiley:

2021-12-30 12:58 UTC, jaen commented
FWIW this fixes my issue with SMTP STARTTLS hanging when it's behind Traefik. Not sure what exactly you've changed to fix it, but thanks a lot! Hope it gets merged soon. Maybe there's a test that can be added so this doesn't regress?

2022-03-08 15:48 UTC, mpl commented on pkg/server/router/tcp/router.go
> +	// httpsForwarder that is used for all HTTPS connections that match
```suggestion
	// for real, the handler returned here is (almost) always the same:
	// it is the httpsForwarder that is used for all HTTPS connections that match
	// (which is also incidentally the same used in the blow below for 404s).
	// The added value from doing Match, is to find and use the specifig TLS config
	// requested for the given HostSNI.
```

2022-03-17 10:00 UTC, kevinpollet commented on pkg/server/server_entrypoint_tcp.go
> +	logger.Debugf("Starting TCP Server")
```suggestion
	logger.Debug("Starting TCP Server")
```

2022-03-17 10:18 UTC, kevinpollet commented on docs/content/routing/routers/index.md
> +     To set the value of a rule, use [backticks](https://en.wiktionary.org/wiki/backtick) ``` ` ``` or escaped double-quotes `\"`.
```suggestion

     To set the value of a rule, use [backticks](https://en.wiktionary.org/wiki/backtick) ``` ` ``` or escaped double-quotes `\"`.
```

2022-03-17 11:19 UTC, tomMoulard commented on pkg/rules/parser.go
> +// Tree represents the rules tree structure.
```suggestion
// Tree represents the rules' tree structure.
```

2022-03-17 11:19 UTC, tomMoulard commented on pkg/server/router/tcp/manager.go
> +			//	connection. Otherwise it will fallback to the default TLS config.
```suggestion
			//	connection. Otherwise, it will fallback to the default TLS config.
```

2022-03-17 11:22 UTC, mpl commented on pkg/muxer/tcp/mux.go
> +		return nil, errors.New("cannot parse")
```suggestion
		return nil, fmt.Errorf("error while parsing rule %s", rule)
```

2022-03-17 11:22 UTC, mpl commented on pkg/muxer/http/mux.go
> +		return nil, errors.New("cannot parse")
```suggestion
		return nil, fmt.Errorf("error while parsing rule %s", rule)
```

2022-03-17 14:56 UTC, kevinpollet commented on pkg/server/router/tcp/router.go
> +			log.WithoutContext().Errorf("Error while reading TCP connection data : %v", err)
```suggestion
			log.WithoutContext().Errorf("Error while reading TCP connection data: %v", err)
```

2022-03-17 14:58 UTC, kevinpollet commented on pkg/muxer/tcp/mux.go
> +			log.WithoutContext().Warnf("\"ClientIP\" matcher: could not match remote address : %v", err)
```suggestion
			log.WithoutContext().Warnf("\"ClientIP\" matcher: could not match remote address: %v", err)
```

2022-03-17 15:00 UTC, kevinpollet commented on pkg/server/router/tcp/router.go
> +		log.WithoutContext().Errorf("Error while reading TCP connection data : %v", err)
```suggestion
		log.WithoutContext().Errorf("Error while reading TCP connection data: %v", err)
```

2022-03-17 16:42 UTC, rtribotte approved these changes
LGTM 👍

2022-03-17 16:43 UTC, tomMoulard approved these changes
LGTM :ok_hand:

2022-03-17 16:44 UTC, mpl approved these changes

2022-03-17 17:02 UTC, merged