Fix ServersTransport reference from IngressRoute service definition
traefik/traefik pull request #8431
Opened 2021-09-09 08:19 UTC by rtribotte

### What does this PR do?

This PR fixes the ServersTransport reference mechanism from an IngressRoute service definition.

It ensures that ServersTransport resources can't override each other when collecting them, by adding the namespace in the key.

It also introduces logic to handle cross-namespacing limitations and also adds the service namespace in the key, when building the service load balancer.

### Motivation

Make it impossible to reference a wrong ServersTransport.

### More

- [x] Added/updated tests
- [x] Added/updated documentation

### Additional Notes

Co-authored-by: Jean-Baptiste Doumenjou <925513+jbdoumenjou@users.noreply.github.com>

2021-09-15 09:50 UTC, jbdoumenjou approved these changes
LGTM

2021-09-15 13:15 UTC, kevinpollet requested changes

2021-09-15 15:07 UTC, kevinpollet approved these changes

2021-09-16 10:14 UTC, tomMoulard approved these changes
LGTM :ok_hand:
Thank you :smiley:

2021-09-16 13:12 UTC, merged