test: upgrade docker-compose
traefik/traefik pull request #8567
Opened 2021-11-10 10:16 UTC by charlie-haley

### What does this PR do?

Removing [libkermit/compose](https://github.com/libkermit/compose) in favour of [docker-compose v2](https://github.com/docker/compose)

### Motivation

[libkermit/compose](https://github.com/libkermit/compose) is deprecated. [docker-compose](https://github.com/docker/compose) has been rebuilt using Go so we can now use it directly.

### More

- [x] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

Co-authored-by: Rémi Buisson <remi.buisson@traefik.io>

2021-11-24 12:46 UTC, rtribotte approved these changes
LGTM 👍

2021-11-25 09:18 UTC, mpl requested changes

2021-11-25 09:18 UTC, mpl commented on integration/tcp_test.go
> +// guessWhoTLSPassthrough guesses service identity and ensure that the certificate is valid for the given server name.
// guessWhoTLSPassthrough guesses service identity and ensures that the
// certificate is valid for the given server name.

2021-11-25 09:52 UTC, mpl approved these changes

2021-11-25 10:10 UTC, merged