Allow HTTP/2 max concurrent stream configuration
traefik/traefik pull request #8781
Opened 2022-02-16 10:22 UTC by tomMoulard

### What does this PR do?

This PR allows configuring the max concurrent stream value of HTTP/2 entrypoint.

### Motivation

Fixes #8768

### More

- [X] Added/updated tests
- [X] Added/updated documentation

2022-02-17 15:39 UTC, rtribotte requested changes

2022-02-17 15:39 UTC, rtribotte commented on docs/content/reference/static-configuration/file.toml
> +      maxConcurrentStreams = 250
```suggestion
      maxConcurrentStreams = 42
```

2022-02-17 15:39 UTC, rtribotte commented on docs/content/reference/static-configuration/file.yaml
> +      maxConcurrentStreams: 250
```suggestion
      maxConcurrentStreams: 42
```

2022-02-17 15:39 UTC, rtribotte commented on docs/content/routing/entrypoints.md
> +          maxConcurrentStreams = 250
```suggestion
          maxConcurrentStreams = 42
```

2022-02-17 15:39 UTC, rtribotte commented on docs/content/routing/entrypoints.md
> +          maxConcurrentStreams: 250
```suggestion
          maxConcurrentStreams: 42
```

2022-02-17 15:39 UTC, rtribotte commented on docs/content/routing/entrypoints.md
> +    --entryPoints.name.http2.maxConcurrentStreams=250
```suggestion
    --entryPoints.name.http2.maxConcurrentStreams=42
```

2022-02-18 08:15 UTC, rtribotte approved these changes
LGTM 👌

2022-02-22 14:52 UTC, tomMoulard commented
The issue should be fixed, removing the `bot/no-merge` label

2022-03-21 14:35 UTC, mpl commented
Summary, explaining why we're delaying on that PR.
we're not seeing any problem at the moment, i.e. the use of x/net seems legitimate for this case, and how we used it seems correct.
However:
- it seems we'll have to keep x/net even more conscientiously updated - at least at every minor Go update, and maybe we have to think more whether that is a cost we are willing to incur
- we're still worried we might be forgetting something, and given we're a reverse-proxy we can't really afford to make mistakes in this area
- and independently, we're realizing that maybe for the h2c case, the http2.Server should have been (even before this PR) initialized with a priority write scheduler, instead of letting it default with a random write scheduler.
TL;DR: we'd like to think about it a bit more, and not rush it for 2.7.

2022-04-04 09:14 UTC, mpl commented on docs/content/reference/static-configuration/cli-ref.md
> +Specifies the number of concurrent streams that each client may have open at a time. (Default: ```250```)
```suggestion
Specifies the number of concurrent streams per connection that each client is allowed to initiate. (Default: ```250```)
```

2022-04-04 09:16 UTC, mpl commented on pkg/config/static/entrypoints.go
> +	MaxConcurrentStreams int32 `description:"Specifies the number of concurrent streams that each client may have open at a time." json:"maxConcurrentStreams,omitempty" toml:"maxConcurrentStreams,omitem
```suggestion
	MaxConcurrentStreams int32 `description:"Specifies the number of concurrent streams per connection that each client is allowed to initiate." json:"maxConcurrentStreams,omitempty" toml:"maxConcurrentStreams,omitempty" yaml:"maxConcurrentStreams,omitempty" export:"true"`
```

2022-04-04 09:17 UTC, mpl commented on docs/content/reference/static-configuration/env-ref.md
> +Specifies the number of concurrent streams that each client may have open at a time. (Default: ```250```)
```suggestion
Specifies the number of concurrent streams per connection that each client is allowed to initiate. (Default: ```250```)
```

2022-04-04 09:21 UTC, mpl commented on docs/content/routing/entrypoints.md
> +`maxConcurrentStreams` defines the number of maximum concurrent streams for HTTP/2.
```suggestion
`maxConcurrentStreams` specifies the number of concurrent streams per connection that each client is allowed to initiate.
```

2022-04-04 09:26 UTC, kevinpollet approved these changes
LGTM

2022-04-04 09:27 UTC, mpl approved these changes

2022-04-04 09:46 UTC, merged

2022-07-29 00:09 UTC, MaxThom commented
Hey @tomMoulard, big thanks to you and all your colleagues.
Its working beautifully! No more node ports everywhere :P