fix: swapping npm to yarn to install webui dependencies
traefik/traefik pull request #8783
Opened 2022-02-17 16:34 UTC by tomMoulard

### What does this PR do?

This PR changes the way that Web UI dependencies are installed through docker.
It now uses [`yarn install`](https://www.npmjs.com/package/yarn) instead of `npm install`.

### Motivation

This PR helps to build the Web UI locally by speeding up the process.

### More

- ~[ ] Added/updated tests~
- ~[ ] Added/updated documentation~

### Additional Notes

For my tests, I saw a decrease of building time going from 201.5s to 32.2s.

I also tried to use [`pnpm`](https://pnpm.io), but it requires more changes on the building process.

2022-02-18 08:13 UTC, rtribotte approved these changes
LGTM 👌

2022-02-18 23:49 UTC, 0xflotus requested changes
You should consider to copy the resulting yarn.lock also to the docker image. 
https://github.com/traefik/traefik/blob/11ff7415121ad4231e7b95d984ab2670f672c371/webui/Dockerfile#L9

Now you copy the package-lock.json. If you use yarn, yarn will create a yarn.lock as equivalent.

2022-02-22 16:03 UTC, 0xflotus commented on webui/Dockerfile
> +COPY yarn.json $WEBUI_DIR/
The file is called `yarn.lock`

2022-02-22 16:05 UTC, 0xflotus approved these changes

2022-03-03 09:55 UTC, kevinpollet requested changes
If we are switching to `yarn`, I would prefer to replace every `npm` command by the `yarn` equivalent to avoid using two different tools for the webui.

2022-03-03 16:48 UTC, kevinpollet approved these changes
LGTM 🚀

2022-03-03 17:08 UTC, merged