Fix log statement for ExternalName misconfig
traefik/traefik pull request #9014
Opened 2022-05-13 18:00 UTC by kruton

### What does this PR do?

When an IngressRoute and an ExternalName do not have matching ports, a
warning is printed to the log. However, it was not formatted so it ended
up looking like:

> time="2022-05-10T07:23:09Z" level=warning msg="The port %d from
IngressRoute doesn't match with ports defined in the ExternalName
service %s/%s.{0 8080 }mynsmyservice"

### Motivation

I saw this error crop up in my Traefik logs. It was helpful, so I thought I'd fix it.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

2022-05-13 18:45 UTC, ldez requested changes

2022-05-13 18:45 UTC, ldez commented on pkg/provider/kubernetes/crd/kubernetes.go
> +			Warning(fmt.Sprintf("The port %d from IngressRoute doesn't match with ports defined in the ExternalName service %s/%s.", port.IntVal, svc.Namespace, svc.Name))
```suggestion
			Warnf("The port %d from IngressRoute doesn't match with ports defined in the ExternalName service %s/%s.", port.IntVal, svc.Namespace, svc.Name)
```

2022-05-16 07:31 UTC, kevinpollet approved these changes
Thanks 👍

2022-05-16 07:34 UTC, rtribotte approved these changes
Thanks 👍

2022-05-16 07:52 UTC, ldez approved these changes
LGTM

2022-05-16 08:00 UTC, merged