Add Tailscale certificate resolver
traefik/traefik pull request #9237
Opened 2022-08-09 15:18 UTC by kevinpollet

### What does this PR do?

This pull request adds Tailscale as a certificate resolver, as publicized in https://tailscale.com/blog/tls-certs/. 

### Motivation

To support Tailscale TLS certificate resolution.

### More

- [X] Added/updated tests
- [X] Added/updated documentation

### Additional Notes

Co-authored-by: Mathieu Lonjaret <mathieu.lonjaret@gmail.com>

2022-08-10 17:32 UTC, mpl approved these changes

2022-08-11 15:15 UTC, rtribotte requested changes

2022-08-11 15:18 UTC, rtribotte commented on cmd/traefik/traefik.go
> +	// Certificates Resolvers.
```suggestion
	// Certificate Resolvers
```

2022-08-11 15:19 UTC, rtribotte approved these changes
LGTM 👌

2022-09-30 13:07 UTC, tomMoulard approved these changes
LGTM :ok_hand:

2022-09-30 13:20 UTC, merged