feat(docs/kubernetes-ingress): Make more clear what options do
traefik/traefik pull request #9380
Opened 2022-09-27 17:04 UTC by samip5

### What does this PR do?

Makes it more clear what the kubernetes-ingress options actually do. like ip and publishedService.

### Motivation

Hackatron and the long lasting issue #8406.

### More

- [x] Added/updated documentation

2022-09-27 23:53 UTC, bwbrock approved these changes
These changes appear good.

2022-09-28 07:36 UTC, rtribotte requested changes

2022-09-28 07:36 UTC, rtribotte commented on docs/content/providers/kubernetes-ingress.md
> +This IP will get copied to ingress status.loadbalancer.ip and currently only supports one IPv4 or IPv6 address.
```suggestion
This IP will get copied to Ingress status.loadbalancer.ip and currently only supports one IP value (IPv4 or IPv6).
```

2022-09-28 07:36 UTC, rtribotte commented on docs/content/providers/kubernetes-ingress.md
> +It will use the services IPs to copy to ingress loadbalancer status, useful for example External-DNS.
```suggestion
The Kubernetes service to copy status from.
When using third parties tools like External-DNS, this option can be used to copy the service loadbalancer.status (containing the service's endpoints IPs) to the ingresses.
```

2022-09-29 07:53 UTC, kevinpollet requested changes

2022-09-29 07:53 UTC, kevinpollet commented on docs/content/providers/kubernetes-ingress.md
> +This IP will get copied to Ingress status.loadbalancer.ip and currently only supports one IP value (IPv4 or IPv6).
```suggestion
This IP will get copied to Ingress `status.loadbalancer.ip` and currently only supports one IP value (IPv4 or IPv6).
```

2022-09-29 07:53 UTC, kevinpollet commented on docs/content/providers/kubernetes-ingress.md
> +When using third parties tools like External-DNS, this option can be used to copy the service loadbalancer.status (containing the service's endpoints IPs) to the ingresses.
```suggestion
When using third parties tools like External-DNS, this option can be used to copy the service `loadbalancer.status` (containing the service's endpoints IPs) to the ingresses.
```

2022-09-29 07:55 UTC, kevinpollet approved these changes
Thanks 👍

2022-09-29 07:55 UTC, rtribotte approved these changes
Thanks 👍

2022-09-29 07:55 UTC, mpl commented on docs/content/providers/kubernetes-ingress.md
> +This IP will get copied to Ingress `status.loadbalancer.ip` and currently only supports one IP value (IPv4 or IPv6).
```suggestion
This IP will get copied to Ingress `status.loadbalancer.ip`, and currently only supports one IP value (IPv4 or IPv6).
```

2022-09-29 07:56 UTC, mpl approved these changes

2022-09-29 08:14 UTC, merged

2024-02-26 03:16 UTC, samip5 commented
Hi @kevinpollet. I'm little sad that you modified the issue description to add the "fixes" as this doesn't in reality fix the underlying bug which is in using Endpoints instead of EndpointSlices. The bug itself is still in the code.

2024-03-05 16:00 UTC, kevinpollet commented
Hello @samip5, and sorry for that, I missed something. 
Could you please open a detailed issue, describing the bug with a reproduction case?

2024-03-05 16:35 UTC, samip5 commented
> Hello @samip5, and sorry for that, I missed something. Could you please open a detailed issue, describing the bug with a reproduction case?

It's right there https://github.com/traefik/traefik/issues/8406.

2024-03-06 10:23 UTC, kevinpollet commented
Hello @samip5,

If I am not mistaken, issue #8406 was about copying the LoadBalancer service IPs to the Ingress status. This is working as expected by using the `publishedService` option and confirmed in the following comment (https://github.com/traefik/traefik/issues/8406#issuecomment-1253675004). This is why I closed the issue, after the clarification you made in the documentation.

The following comment https://github.com/traefik/traefik/issues/8406#issuecomment-907221953 is about the IPs used for load balancing, which seems to contain only one IP Family. If there is an issue with IPv6 or dual stack clusters, it would be easier to open a new issue to be able to address it properly.

Could you please open this new issue describing the problem?

2024-03-06 15:36 UTC, samip5 commented
> Hello @samip5,
> 
> If I am not mistaken, issue #8406 was about copying the LoadBalancer service IPs to the Ingress status. This is working as expected by using the `publishedService` option and confirmed in the following comment ([#8406 (comment)](https://github.com/traefik/traefik/issues/8406#issuecomment-1253675004)). This is why I closed the issue, after the clarification you made in the documentation.
> 
> The following comment [#8406 (comment)](https://github.com/traefik/traefik/issues/8406#issuecomment-907221953) is about the IPs used for load balancing, which seems to contain only one IP Family. If there is an issue with IPv6 or dual stack clusters, it would be easier to open a new issue to be able to address it properly.
> 
> Could you please open this new issue describing the problem?

You're unfortunately mistaken, as the original one was also about EndpointSlices, not just copying the status.

2024-03-07 14:09 UTC, emilevauge commented
Hi @samip5 
I propose that you open a specific issue to explain your problem.
Thank you

2024-03-08 13:55 UTC, samip5 commented
> Hi @samip5 I propose that you open a specific issue to explain your problem. Thank you

It already has been explained (multiple times, mind you, even in the Hackathon), but no matter how I try to explain it, it seems maintainers will not understand my point, so I will rather just not use Traefik.

2024-03-08 13:58 UTC, emilevauge commented
I'm sorry, but that's how most open source project works: _to report problems through issues_.
This is the only way to avoid confusion and understand your use case (which is not the case today).
Don't hesitate to come back later if you want to contribute.